// The public C ABI for the Flutter UI. This is the only header the Dart FFI
// bindings (app_flutter/lib/data/ffi/gbm_bindings.dart, generated by ffigen)
// are generated from, and the only header anything outside src/capi should
// include. Everything here is extern "C": no C++ types cross this boundary.
//
// Two data-marshalling conventions are used, matching the plan's "JSON for
// structured/low-frequency data, packed binary for the graph" split:
//
//  * Scalar calls (checkout, ...) take plain C parameters and return an
//    int32_t status: 0 or positive on success, a negative value that is the
//    negated ordinal of gbm::GitError::Code on failure (0 = Unknown, -1 =
//    Unknown, i.e. negate-then-subtract-one avoided: see GBM_ERR below).
//  * Structured snapshots (repo state, discovered repos) are returned as
//    JSON through a thread-local staging buffer: call the function that
//    produces the result, then gbm_last_result_json_len() and
//    gbm_last_result_json_copy() immediately after, on the same thread.
//  * The commit graph is exposed as packed binary buffers
//    (gbm_graph_snapshot_*) whose layout matches gbm::GraphSnapshot exactly
//    -- see src/core/graph/GraphSnapshot.h. These are zero-copy views valid
//    until the next gbm_graph_snapshot_rows() call for the same session or
//    an explicit gbm_graph_snapshot_release().
//  * Asynchronous results (history refresh, checkout) are delivered through
//    a per-session event callback registered with gbm_register_callback().
//    The callback may be invoked from any native thread -- a ThreadPool
//    worker or the operation runner's serial thread -- never from the
//    thread that called gbm_register_callback(). On the Dart side this is
//    exactly what NativeCallable.listener is for. A non-empty payload is
//    heap-allocated by this library and MUST be released by calling
//    gbm_free_event_payload() once the receiver is done reading it.

#pragma once

#include <stdint.h>

#if defined(_WIN32)
#define GBM_API extern "C" __declspec(dllexport)
#else
#define GBM_API extern "C" __attribute__((visibility("default")))
#endif

// --- Handles -----------------------------------------------------------

typedef void* GbmSessionHandle;
typedef void* GbmDiscoveryHandle;

// --- Errors --------------------------------------------------------------
// Mirrors gbm::GitError::Code (src/core/base/Error.h) 1:1. A scalar call
// returns 0 on success and -(1 + code-ordinal) on failure, so GBM_ERR_UNKNOWN
// (ordinal 0) maps to -1 and 0 stays unambiguously "success".

enum GbmErrorCode {
    GBM_ERR_UNKNOWN = 0,
    GBM_ERR_NOT_FOUND = 1,
    GBM_ERR_INVALID_ARGUMENT = 2,
    GBM_ERR_CONFLICT = 3,
    GBM_ERR_LOCK_HELD = 4,
    GBM_ERR_AUTH = 5,
    GBM_ERR_HOST_KEY = 6,
    GBM_ERR_NON_FAST_FORWARD = 7,
    GBM_ERR_DIRTY_WORK_TREE = 8,
    GBM_ERR_HOOK_REJECTED = 9,
    GBM_ERR_CANCELLED = 10,
    GBM_ERR_PROCESS_FAILED = 11,
    GBM_ERR_SPAWN_FAILED = 12,
    GBM_ERR_PARSE_ERROR = 13,
    GBM_ERR_CORRUPT = 14,
    GBM_ERR_UNSUPPORTED = 15,
    GBM_ERR_TIMEOUT = 16,
    GBM_ERR_TOO_LARGE = 17,
    GBM_ERR_DATABASE = 18,
    GBM_ERR_IO = 19,
};

// --- Events ----------------------------------------------------------------
// One ordinal per RepositorySession Qt signal this bridge replaces (see
// src/app/bridge/RepositorySession.h:505-598). Only the M0/M1 subset is
// defined so far; later milestones extend this enum, never renumber it.

enum GbmEventType {
    GBM_EVENT_GRAPH_UPDATED = 0,   ///< payload: {"complete": bool}
    GBM_EVENT_REFS_UPDATED = 1,    ///< no payload
    GBM_EVENT_ERROR_OCCURRED = 2,  ///< payload: GitError JSON
    /// payload: OperationOutcome JSON: {"succeeded": bool, "error": GitError
    /// JSON | null, "choices": OperationChoice[], "summary": string,
    /// "kind"?: string}. "kind" is present only for operations that stamp one
    /// -- currently "checkout" (gbm_branch_checkout) and "delete-branch"
    /// (gbm_branch_delete) -- so a caller juggling more than one in-flight
    /// request on this shared channel can match an outcome back to the
    /// request that produced it instead of assuming the next event to arrive
    /// must be the answer.
    GBM_EVENT_OPERATION_FINISHED = 3,

    /// no payload; read the new status with gbm_working_copy_status_json().
    GBM_EVENT_WORKING_COPY_STATUS_UPDATED = 4,
    /// payload: OperationOutcome JSON. Fired by stage/unstage/commit.
    GBM_EVENT_WORKING_COPY_OPERATION_FINISHED = 5,
    /// payload: {"path": string, "staged": bool, "diff": ParsedDiff JSON}.
    /// Reply to gbm_working_copy_diff_json(); the echoed path/staged let a
    /// caller that issued several diff requests match replies back up.
    GBM_EVENT_WORKING_COPY_DIFF_READY = 6,

    /// no payload; read the new list with gbm_stashes_json().
    GBM_EVENT_STASHES_UPDATED = 7,
    /// payload: {"index": int, "diff": ParsedDiff JSON}. Reply to
    /// gbm_stash_request_diff().
    GBM_EVENT_STASH_DIFF_READY = 8,
    /// no payload; read the new list with gbm_worktrees_json().
    GBM_EVENT_WORKTREES_UPDATED = 9,
    /// no payload; read the new list with gbm_remotes_json().
    GBM_EVENT_REMOTES_UPDATED = 10,
    /// payload: {"prompt": string}. A `git` subprocess spawned by a
    /// fetch/pull/push/remote-tag-delete is blocked waiting for a username
    /// or password -- reply with gbm_provide_credential() or
    /// gbm_cancel_credential(). See gbm_provide_credential()'s doc comment
    /// for why a follow-up prompt in the same operation fires this again.
    GBM_EVENT_CREDENTIAL_REQUESTED = 11,
    /// payload: OperationRecord JSON. Fired once per `git` invocation this
    /// session makes, for an operation-log panel -- see
    /// core/base/Logging.h's OperationRecord doc comment. Distinct from
    /// every other event: it can fire during a *read* (history refresh,
    /// working-copy refresh), not only a mutation.
    GBM_EVENT_OPERATION_LOG_RECORD = 12,

    /// payload: BlameResult JSON. Reply to gbm_request_blame().
    GBM_EVENT_BLAME_READY = 13,
    /// payload: FileHistoryEntry JSON array. Reply to
    /// gbm_request_file_history().
    GBM_EVENT_FILE_HISTORY_READY = 14,
    /// payload: LineHistoryChunk JSON array. Reply to
    /// gbm_request_line_history().
    GBM_EVENT_LINE_HISTORY_READY = 15,
    /// payload: ReflogEntry JSON array. Reply to gbm_request_reflog().
    GBM_EVENT_REFLOG_READY = 16,

    /// payload: RebaseTodoEntry JSON array. Reply to
    /// gbm_request_rebase_plan().
    GBM_EVENT_REBASE_PLAN_READY = 17,
    /// no payload; read the new list with gbm_submodules_json().
    GBM_EVENT_SUBMODULES_UPDATED = 18,
    /// no payload; read the new status with gbm_bisect_status_json().
    GBM_EVENT_BISECT_STATUS_UPDATED = 19,
    /// no payload; read installation/patterns/files with
    /// gbm_lfs_installation_json()/gbm_lfs_patterns_json()/
    /// gbm_lfs_files_json().
    GBM_EVENT_LFS_UPDATED = 20,
    /// payload: CleanEntry JSON array. Reply to gbm_clean_preview().
    GBM_EVENT_CLEAN_PREVIEW_READY = 21,

    /// no payload; read with gbm_local_identity_json().
    GBM_EVENT_LOCAL_IDENTITY_UPDATED = 22,
    /// no payload; read with gbm_effective_identity_json().
    GBM_EVENT_EFFECTIVE_IDENTITY_UPDATED = 23,
    /// payload: {"succeeded": bool}. Reply to gbm_write_commit_graph() --
    /// separate from GBM_EVENT_OPERATION_FINISHED/WORKING_COPY_OPERATION_
    /// FINISHED so a caller reacting to the perf-advice banner does not have
    /// to filter every operation outcome for the one it recognises.
    GBM_EVENT_COMMIT_GRAPH_WRITE_FINISHED = 24,
    /// payload: {"path": string, "content": string, "editable": bool}.
    /// Reply to gbm_request_working_tree_content(). `content` is empty and
    /// `editable` is false when the file is binary, contains an embedded
    /// NUL, is not well-formed UTF-8, or exceeds the display size cap.
    GBM_EVENT_WORKING_TREE_CONTENT_READY = 25,
    /// payload: CommitMeta JSON array, in the same order as the requested
    /// oids. Reply to gbm_request_commit_meta(). An oid git could not read
    /// is simply absent from the array rather than failing the whole batch
    /// -- see CommitMetaStore::read()'s doc comment.
    GBM_EVENT_COMMIT_META_READY = 26,
    /// payload: {"oid": string, "files": ChangedFile JSON array}. Reply to
    /// gbm_request_commit_files().
    GBM_EVENT_COMMIT_FILES_READY = 27,
    /// payload: {"oid": string, "path": string, "diff": ParsedDiff JSON}.
    /// Reply to gbm_request_commit_file_diff().
    GBM_EVENT_COMMIT_FILE_DIFF_READY = 28,

    /// payload: {"left": string, "right": string, "threeDot": bool,
    /// "mergeBase": string, "commits": CompareCommitEntry JSON array,
    /// "files": DiffFile JSON array}. Reply to gbm_request_compare_refs().
    /// "mergeBase" is "" when the two refs share no common ancestor -- that
    /// is a valid result to display (unrelated histories), not an error.
    /// left/right/threeDot are echoed back from the request so a caller
    /// with several Compare tabs open at once (each its own ref pair) can
    /// match this reply to the tab that asked for it -- see
    /// Session::requestCompareRefs()'s doc comment.
    GBM_EVENT_COMPARE_READY = 29,
    /// payload: {"left": string, "right": string, "threeDot": bool, "path":
    /// string, "diff": ParsedDiff JSON}. Reply to
    /// gbm_request_compare_file_diff(), same echo-the-request reasoning as
    /// GBM_EVENT_COMPARE_READY above.
    GBM_EVENT_COMPARE_FILE_DIFF_READY = 30,
    /// payload: {"remote": string, "refs": RemotePrunePreviewEntry JSON
    /// array}. Reply to gbm_request_remote_prune_preview(). The real
    /// deletion (gbm_remote_prune()) reports through the existing
    /// GBM_EVENT_OPERATION_FINISHED instead of a dedicated event -- it is
    /// an Operation like fetch/pull/push/branch-delete, not a new kind of
    /// reply.
    GBM_EVENT_REMOTE_PRUNE_PREVIEW_READY = 31,
    /// payload: {"ref": string, "diff": ParsedDiff JSON}. Reply to
    /// gbm_request_compare_with_working_copy() -- the "compare a ref with
    /// Working Copy" side of the Compare tab, backed by
    /// DiffService::commitVsWorkingTree(). "ref" is echoed back from the
    /// request for the same multi-tab matching reason as
    /// GBM_EVENT_COMPARE_READY. Unlike that event, there is no
    /// "threeDot"/"mergeBase" to echo -- a working-tree diff has only one
    /// commit on either side, so two-dot/three-dot and merge-base have no
    /// meaning here.
    GBM_EVENT_COMPARE_WITH_WORKING_COPY_READY = 32,
    /// payload: {"message": string}. Reply to
    /// gbm_request_original_operation_message(). "message" is git's own
    /// proposed commit message for the merge/cherry-pick/revert/rebase
    /// currently stopped on conflicts (subject, body, and any "# Conflicts:"
    /// listing, verbatim -- comment lines are not stripped, since whether to
    /// render them differently is a UI concern). Empty when no operation is
    /// in progress or git prepared no message at all -- not an error.
    GBM_EVENT_ORIGINAL_OPERATION_MESSAGE_READY = 33,
    /// payload: {"revision": string, "path": string, "destPath": string,
    /// "succeeded": bool, "error": GitError JSON (only when succeeded is
    /// false)}. Reply to gbm_export_file_at_revision(). All three request
    /// parameters are echoed back so a caller with several exports in
    /// flight can match the reply to the one it is waiting on -- the same
    /// per-request matching GBM_EVENT_COMPARE_READY uses. Unlike the
    /// best-effort reads above this reports failure explicitly rather than
    /// as an empty success: the caller is about to hand `destPath` to the
    /// OS or tell the user their file was saved, and neither is safe to do
    /// on a guess.
    GBM_EVENT_FILE_AT_REVISION_EXPORTED = 34,
};

typedef void (*GbmEventCallback)(GbmSessionHandle session,
                                 int32_t eventType,
                                 const uint8_t* payload,
                                 int32_t payloadLen,
                                 void* userData);

/// Frees a payload buffer handed to a GbmEventCallback. Safe to call only
/// once per payload, and only after the callback that received it has
/// finished reading it. A null or already-freed pointer is not accepted.
GBM_API void gbm_free_event_payload(const uint8_t* payload);

// --- Thread-local synchronous-result staging buffer -------------------------
// Populated by any function documented "populates the staging buffer".
// Always drain it (len, then copy) on the same thread and before the next
// such call on that thread -- it is thread-local, not per-session.

GBM_API int32_t gbm_last_result_json_len(void);
GBM_API void gbm_last_result_json_copy(uint8_t* out, int32_t outLen);

// --- Session lifecycle -------------------------------------------------

/// Opens a repository. `commonDir` may be empty (defaults to gitDir) for a
/// non-worktree repository. Detects the git executable fresh each call is
/// avoided: detection is cached process-wide after the first successful
/// open. Returns null and populates the staging buffer with a GitError JSON
/// on failure (e.g. no usable git on PATH).
GBM_API GbmSessionHandle gbm_session_open(const char* workDir,
                                          const char* gitDir,
                                          const char* commonDir);

/// Cancels any in-flight work and releases the session. `session` must not
/// be used again afterwards.
GBM_API void gbm_session_close(GbmSessionHandle session);

/// Registers the event callback for this session. Replaces any previously
/// registered callback. Must be called before any async-producing call
/// (gbm_history_refresh, gbm_branch_checkout) if events are to be observed.
GBM_API void gbm_register_callback(GbmSessionHandle session,
                                   GbmEventCallback callback,
                                   void* userData);

// --- Repository state --------------------------------------------------

/// Populates the staging buffer with the current RepoState as JSON.
/// Returns 0 on success.
GBM_API int32_t gbm_repo_state_json(GbmSessionHandle session);

// --- History / graph -----------------------------------------------------

/// Requests a refs + history refresh. Runs on a shared background worker;
/// never blocks the calling thread. Fires GBM_EVENT_REFS_UPDATED once refs
/// are read, then one or more GBM_EVENT_GRAPH_UPDATED as the walk streams
/// (the last has payload {"complete": true}), or GBM_EVENT_ERROR_OCCURRED on
/// failure.
GBM_API void gbm_history_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published RefSnapshot
/// (branches, tags, HEAD) as JSON. Returns 0 on success, or a negative
/// GbmErrorCode if gbm_history_refresh() has not yet published one.
GBM_API int32_t gbm_refs_json(GbmSessionHandle session);

/// Row-parallel packed GraphSnapshot::RowMeta buffer (16 bytes/row, see
/// src/core/graph/GraphSnapshot.h). Pins the underlying snapshot until the
/// next call to this function for the same session or
/// gbm_graph_snapshot_release(). Null with *rowCount == 0 if no snapshot has
/// been published yet.
GBM_API const uint8_t* gbm_graph_snapshot_rows(GbmSessionHandle session,
                                               int32_t* rowCount,
                                               int32_t* rowStride);

/// Packed ObjectId buffer, one 33-byte entry per row, same row order and
/// pinning as gbm_graph_snapshot_rows().
GBM_API const uint8_t* gbm_graph_snapshot_oids(GbmSessionHandle session,
                                               int32_t* oidCount,
                                               int32_t* oidStride);

/// Packed RowId (uint32) parent-pool buffer; see RowMeta::parentOffset.
GBM_API const uint32_t* gbm_graph_snapshot_parents(GbmSessionHandle session, int32_t* parentCount);

/// Packed GraphSnapshot::Edge buffer (16 bytes/edge).
GBM_API const uint8_t* gbm_graph_snapshot_edges(GbmSessionHandle session,
                                                int32_t* edgeCount,
                                                int32_t* edgeStride);

/// Requests the changed-files list for a commit. Async: fires
/// GBM_EVENT_COMMIT_FILES_READY with a ChangedFile JSON array, or
/// GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_request_commit_files(GbmSessionHandle session, const char* oid);

/// Requests the full diff for a specific file in a commit. Async: fires
/// GBM_EVENT_COMMIT_FILE_DIFF_READY with a ParsedDiff JSON payload, or
/// GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_request_commit_file_diff(GbmSessionHandle session,
                                          const char* oid,
                                          const char* path);

// --- Compare (M6) ----------------------------------------------------------
// Two-ref comparison queries backing the Compare tab (spec page 12): unlike
// gbm_remotes_json() (one published "current" snapshot), a Compare tab's
// inputs are two user-chosen refs and the UI allows several tabs open at
// once with different ref pairs -- so these follow the same
// echo-the-request-params-back pattern as gbm_request_commit_file_diff()
// above, not the single-published-state pattern. Both are read-only.

/// Requests merge-base + the commit lists unique to each side + the
/// changed-file summary for two refs, in one round trip (opening a Compare
/// tab always wants all three). `threeDot` non-zero: `left...right`
/// (symmetric difference off the merge base). Zero: `left..right` (only
/// what right has that left doesn't). Async: fires GBM_EVENT_COMPARE_READY,
/// or GBM_EVENT_ERROR_OCCURRED on failure (e.g. either ref empty).
GBM_API void gbm_request_compare_refs(GbmSessionHandle session,
                                      const char* leftRef,
                                      const char* rightRef,
                                      int32_t threeDot);

/// Requests one file's full diff between two refs. Async: fires
/// GBM_EVENT_COMPARE_FILE_DIFF_READY, or GBM_EVENT_ERROR_OCCURRED on
/// failure.
GBM_API void gbm_request_compare_file_diff(GbmSessionHandle session,
                                           const char* leftRef,
                                           const char* rightRef,
                                           int32_t threeDot,
                                           const char* path);

/// Requests the diff between `ref` and the live working tree (uncommitted
/// changes included) -- the "compare a ref with Working Copy" side of the
/// Compare tab. `ref` may be any revision expression git accepts (branch,
/// tag, oid, HEAD~N, ...); it is resolved to a commit internally. Async:
/// fires GBM_EVENT_COMPARE_WITH_WORKING_COPY_READY, or
/// GBM_EVENT_ERROR_OCCURRED on failure (e.g. `ref` does not resolve).
GBM_API void gbm_request_compare_with_working_copy(GbmSessionHandle session, const char* ref);

GBM_API int32_t gbm_graph_snapshot_lane_count(GbmSessionHandle session);
GBM_API int32_t gbm_graph_snapshot_complete(GbmSessionHandle session);
GBM_API int32_t gbm_graph_snapshot_truncated(GbmSessionHandle session);

/// Releases the pinned snapshot from the last gbm_graph_snapshot_rows() call.
/// Safe to call even if nothing is pinned.
GBM_API void gbm_graph_snapshot_release(GbmSessionHandle session);

// --- Branches ------------------------------------------------------------

/// `git switch`/`git checkout`. Async: fires GBM_EVENT_OPERATION_FINISHED
/// with an OperationOutcome JSON payload, and on success also triggers the
/// same refresh gbm_history_refresh() would (so REFS_UPDATED/GRAPH_UPDATED
/// follow). String parameters must be UTF-8 and non-null (pass "" for
/// absent); boolean parameters are 0/1.
GBM_API void gbm_branch_checkout(GbmSessionHandle session,
                                 const char* target,
                                 int32_t detach,
                                 int32_t createBranch,
                                 const char* newBranchName,
                                 int32_t force,
                                 int32_t stashFirst,
                                 int32_t recurseSubmodules);

/// `git branch <name> [<startPoint>]`, optionally followed by a checkout
/// and/or `--track`/`-u <upstream>`. `startPoint` empty means HEAD. Async:
/// fires GBM_EVENT_OPERATION_FINISHED, and on success refreshes refs (and
/// history, if `checkoutAfter` moved HEAD).
GBM_API void gbm_branch_create(GbmSessionHandle session,
                               const char* name,
                               const char* startPoint,
                               int32_t checkoutAfter,
                               int32_t setUpstream,
                               const char* upstream);

/// `git branch -m <from> <to>` (`-M` when `force`).
///
/// When `renameRemote` is set, the rename is carried through to
/// `remoteName` afterwards: `git push --set-upstream <remoteName> <to>`,
/// then `git push <remoteName> --delete <from>`. git has no atomic remote
/// rename, so it really is push-then-delete -- everyone else's
/// remote-tracking ref for the old name goes `gone`. A failure in either
/// remote step is reported as a failed operation whose summary states that
/// the *local* rename did land, since the caller otherwise cannot tell
/// which half happened.
///
/// When `renameRemote` is not set, the branch's upstream is unset instead:
/// `git branch -m` carries the tracking config across, which would leave
/// the renamed branch tracking the old remote branch.
///
/// Async: fires GBM_EVENT_OPERATION_FINISHED, and on success refreshes
/// refs. May fire GBM_EVENT_CREDENTIAL_REQUESTED while `renameRemote` is
/// contacting the remote.
GBM_API void gbm_branch_rename(GbmSessionHandle session,
                               const char* from,
                               const char* to,
                               int32_t force,
                               int32_t renameRemote,
                               const char* remoteName);

/// `git branch -d/-D <names...>` (multiple names in one call, matching
/// `git branch`'s own multi-name support -- a multi-select delete is one
/// operation, not N), or `git push <remoteName> --delete <names...>` when
/// `isRemote`. `force` deletes even when not fully merged. Async: fires
/// GBM_EVENT_OPERATION_FINISHED, and on success refreshes refs.
GBM_API void gbm_branch_delete(GbmSessionHandle session,
                               const char* const* names,
                               int32_t nameCount,
                               int32_t force,
                               int32_t isRemote,
                               const char* remoteName);

// --- Reset -----------------------------------------------------------------
// Mirrors RepositorySession::resetTo -- see src/core/git/ops/ResetOps.h.

/// `mode`: 0 = soft, 1 = mixed, 2 = hard (ResetMode's ordinal order in
/// ResetOps.h: Soft, Mixed, Hard). `target` empty means HEAD. Async: fires
/// GBM_EVENT_OPERATION_FINISHED, and on success also triggers both a
/// history refresh (HEAD moved) and a working-copy refresh (mixed/hard
/// rewrite the index and/or work tree).
GBM_API void gbm_reset_to(GbmSessionHandle session, const char* target, int32_t mode);

// --- Merge -------------------------------------------------------------
// Mirrors RepositorySession::mergeBranch/abortMerge -- see
// src/core/git/ops/MergeOps.h.

/// `mode`: 0 = fast-forward-only, 1 = no-fast-forward, 2 = squash
/// (MergeMode's ordinal order: FastForwardOnly, NoFastForward, Squash).
/// `message` overrides the default merge commit message (ignored for
/// squash); pass "" to use git's default. Async: fires
/// GBM_EVENT_OPERATION_FINISHED. A conflicting merge is reported with
/// `succeeded: false` and `error.code` == GBM_ERR_CONFLICT, exactly like any
/// other outcome -- it is not a crash or an exceptional case, see
/// MergeOps.h's doc comment. Either way the working copy is refreshed so
/// conflicted paths show up; history is refreshed only on success.
GBM_API void gbm_merge_branch(GbmSessionHandle session,
                              const char* target,
                              int32_t mode,
                              const char* message,
                              int32_t stashFirst);

/// `git merge --abort`. Async: fires GBM_EVENT_OPERATION_FINISHED.
GBM_API void gbm_merge_abort(GbmSessionHandle session);

// --- Cherry-pick -----------------------------------------------------------
// Mirrors RepositorySession::cherryPick/continueCherryPick/skipCherryPick/
// abortCherryPick -- see src/core/git/ops/CherryPickOps.h.

/// `commitHexes`/`commitCount`: full or abbreviated hex object ids, oldest
/// first (the order they are applied in). `mainline` is 1-based, 0 means
/// "not a merge commit". Async: fires GBM_EVENT_OPERATION_FINISHED; stops at
/// the first conflict exactly like `git cherry-pick`, leaving the remaining
/// commits queued for gbm_cherry_pick_continue()/_skip()/_abort().
GBM_API void gbm_cherry_pick(GbmSessionHandle session,
                             const char* const* commitHexes,
                             int32_t commitCount,
                             int32_t mainline,
                             int32_t noCommit,
                             int32_t stashFirst);

GBM_API void gbm_cherry_pick_continue(GbmSessionHandle session);
GBM_API void gbm_cherry_pick_skip(GbmSessionHandle session);
GBM_API void gbm_cherry_pick_abort(GbmSessionHandle session);

/// Same as gbm_cherry_pick_continue(), except `message` (a caller-edited
/// commit message, typically pre-filled from
/// GBM_EVENT_ORIGINAL_OPERATION_MESSAGE_READY) overwrites MERGE_MSG before
/// continuing, so it becomes the resulting commit's message instead of
/// git's own proposal. A separate function rather than a parameter added to
/// gbm_cherry_pick_continue() -- see that function's callers, which have no
/// message to pass and should not need one. Async: fires
/// GBM_EVENT_OPERATION_FINISHED, same as gbm_cherry_pick_continue().
GBM_API void gbm_cherry_pick_continue_with_message(GbmSessionHandle session, const char* message);

// --- Revert ------------------------------------------------------------
// Mirrors RepositorySession::revertCommit -- see src/core/git/ops/RevertOps.h.

/// Same `commitHexes`/`commitCount` convention as gbm_cherry_pick(). Async:
/// fires GBM_EVENT_OPERATION_FINISHED. No continue/skip/abort entry point --
/// see RevertOps.h's doc comment for why.
GBM_API void gbm_revert(GbmSessionHandle session,
                        const char* const* commitHexes,
                        int32_t commitCount,
                        int32_t noCommit,
                        int32_t stashFirst);

// --- Conflict resolution -----------------------------------------------
// Mirrors RepositorySession::resolveConflict -- see
// src/core/git/ops/ConflictOps.h.

/// `resolution`: 0 = take ours, 1 = take theirs, 2 = mark resolved (stage
/// current on-disk content as-is), 3 = write resolved (write
/// `resolvedContent` to `path` first, then stage it) -- ConflictResolution's
/// ordinal order in ConflictOps.h. `oursBlobMissing`/`theirsBlobMissing`
/// matter only for take-ours/take-theirs (see WorkingCopyEntry::oursBlob/
/// theirsBlob's doc comments); `resolvedContent` matters only for
/// write-resolved and must be non-empty then. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED (this is a working-copy-scoped
/// fix, not a top-level branch operation), and refreshes the working copy
/// on success.
GBM_API void gbm_resolve_conflict(GbmSessionHandle session,
                                  const char* path,
                                  int32_t resolution,
                                  int32_t oursBlobMissing,
                                  int32_t theirsBlobMissing,
                                  const char* resolvedContent);

/// Reads git's own proposed commit message for the merge/cherry-pick/
/// revert/rebase currently stopped on conflicts, so the conflict resolution
/// window's Continue step can show it as an editable pre-fill -- see
/// gbm_cherry_pick_continue_with_message()/gbm_rebase_continue_with_message().
/// Async: fires GBM_EVENT_ORIGINAL_OPERATION_MESSAGE_READY.
GBM_API void gbm_request_original_operation_message(GbmSessionHandle session);

/// Reads a conflicted path's raw on-disk content (conflict markers and all)
/// for the resolve editor -- a conflicted path has no stage 0, so it cannot
/// be read via a `revision:path` cat-file lookup the way an ordinary
/// tracked file's content can; the markers exist only on disk. Async: fires
/// GBM_EVENT_WORKING_TREE_CONTENT_READY. Best-effort: a missing/unreadable
/// file reports `editable: false` with empty content, not
/// GBM_EVENT_ERROR_OCCURRED -- see that event's doc comment.
GBM_API void gbm_request_working_tree_content(GbmSessionHandle session, const char* path);

/// Splits `content` (typically a gbm_request_working_tree_content() reply)
/// into plain-text and per-region conflict segments, populating the
/// staging buffer with the result as JSON -- see ConflictMarkerParser's
/// doc comment in core/git/ConflictMarkerParser.h for the exact parsing
/// rules (diff3 `|||||||` base, CRLF/no-trailing-newline preservation, and
/// the regionCount==0 fallback for malformed markers). Pure and
/// session-independent: does not touch git or the filesystem. Returns 0 on
/// success.
GBM_API int32_t gbm_parse_conflict_markers(const char* content);

// --- Working copy / diff ---------------------------------------------------
// Mirrors RepositorySession's working-copy methods (RepositorySession.h,
// "Working Copy" section) and DiffService's workingTreeDiff -- see
// src/core/git/WorkingCopyStatus.h and src/core/git/DiffService.h.

/// Re-reads `git status`. Deliberately uncached (see WorkingCopyStatusReader's
/// doc comment: the work tree changes on every keystroke), so this always
/// runs a fresh scan. Async: fires GBM_EVENT_WORKING_COPY_STATUS_UPDATED on
/// success or GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_working_copy_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published
/// WorkingCopyStatus as JSON. Returns 0 on success, or a negative
/// GbmErrorCode if gbm_working_copy_refresh() has not yet published one.
GBM_API int32_t gbm_working_copy_status_json(GbmSessionHandle session);

/// Diff of one path: work tree vs index (staged=0) or index vs HEAD
/// (staged=1). Async: fires GBM_EVENT_WORKING_COPY_DIFF_READY.
GBM_API void gbm_working_copy_diff(GbmSessionHandle session, const char* path, int32_t staged);

/// `git add -- <paths>`. `paths`/`pathCount` describe a plain C array of
/// UTF-8 C strings. Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED,
/// and on success also triggers gbm_working_copy_refresh().
GBM_API void gbm_stage_files(GbmSessionHandle session, const char* const* paths, int32_t pathCount);

/// `git restore --staged -- <paths>`. Same event/refresh contract as
/// gbm_stage_files().
GBM_API void gbm_unstage_files(GbmSessionHandle session,
                               const char* const* paths,
                               int32_t pathCount);

/// Stages a single hunk from `path`'s unstaged diff (work tree vs index):
/// recomputes that diff, locates hunk number `hunkIndex` (0-based, in the
/// same order gbm_working_copy_diff's reply lists them), and applies it to
/// the index only via `git apply --cached`. Same event/refresh contract as
/// gbm_stage_files(); fails with succeeded=false if `hunkIndex` no longer
/// exists (the file changed since it was last diffed) -- see
/// PartialStageRequest's doc comment in core/git/ops/StageOps.h.
GBM_API void gbm_stage_hunk(GbmSessionHandle session, const char* path, int32_t hunkIndex);

/// The reverse of gbm_stage_hunk(): recomputes `path`'s *staged* diff (index
/// vs HEAD), locates hunk `hunkIndex` there, and applies it with `git apply
/// --cached --reverse`. Same event/refresh contract as gbm_stage_files().
GBM_API void gbm_unstage_hunk(GbmSessionHandle session, const char* path, int32_t hunkIndex);

/// Like gbm_stage_hunk(), but stages only a subset of that hunk's added/
/// removed lines -- `lineIndices`/`lineIndexCount` index into the hunk's
/// `lines` array (context and no-newline-marker lines always pass through
/// regardless of whether their index is included). Same event/refresh
/// contract as gbm_stage_files().
GBM_API void gbm_stage_lines(GbmSessionHandle session,
                             const char* path,
                             int32_t hunkIndex,
                             const int32_t* lineIndices,
                             int32_t lineIndexCount);

/// The reverse of gbm_stage_lines(): recomputes `path`'s *staged* diff,
/// applied with `git apply --cached --reverse`. Same event/refresh contract
/// as gbm_stage_files().
GBM_API void gbm_unstage_lines(GbmSessionHandle session,
                               const char* path,
                               int32_t hunkIndex,
                               const int32_t* lineIndices,
                               int32_t lineIndexCount);

/// Discards a subset of a hunk's added/removed lines from the *work tree*
/// -- context menu 05-G's "Discard N lines…". Same arguments as
/// gbm_stage_lines(), and `lineIndices`/`lineIndexCount` index into the
/// hunk's `lines` array the same way (empty discards the whole hunk).
///
/// The difference from gbm_unstage_lines() is which of the two things git
/// tracks gets rewritten: the three functions above all run `git apply
/// --cached`, so only the index moves and the file on disk is untouched.
/// This one drops `--cached`, so git rewrites the file itself and the index
/// is left alone. It is destructive in the same way `git restore` is --
/// the discarded content is not in the reflog, the stash, or anywhere else
/// -- so the caller is expected to confirm first (spec page 06's Discard
/// changes dialog).
///
/// Always resolved against the *unstaged* diff (work tree vs index); there
/// is no `staged` variant, because discarding a staged change is unstaging,
/// which gbm_unstage_lines() already does. Same event/refresh contract as
/// gbm_stage_lines(). A hunk index that no longer matches fails cleanly
/// with the work tree untouched, exactly as gbm_stage_hunk() does.
GBM_API void gbm_discard_lines(GbmSessionHandle session,
                               const char* path,
                               int32_t hunkIndex,
                               const int32_t* lineIndices,
                               int32_t lineIndexCount);

/// `git commit` / `git commit --amend`. `message` empty together with
/// `amend` keeps the existing message (`--amend --no-edit`); empty otherwise
/// is rejected before git runs. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success also triggers
/// both gbm_working_copy_refresh() and the same refresh
/// gbm_history_refresh() would (the new commit needs to appear in the
/// graph).
GBM_API void gbm_commit_changes(GbmSessionHandle session,
                                const char* message,
                                int32_t amend,
                                int32_t signOff);

// --- Stashes -----------------------------------------------------------
// Mirrors RepositorySession's "M3: stashes" section -- see
// src/core/git/ops/StashOps.h.

/// Re-reads `git stash list`. Async: fires GBM_EVENT_STASHES_UPDATED on
/// success or GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_stash_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published stash list
/// as a JSON array. Returns 0 on success, or a negative GbmErrorCode if
/// gbm_stash_refresh() has not yet published one.
GBM_API int32_t gbm_stashes_json(GbmSessionHandle session);

/// `git stash push`. `paths`/`pathCount` restrict the stash to those paths,
/// like gbm_stage_files(); an empty array stashes every changed path. Async:
/// fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success also
/// refreshes both the working copy and the stash list.
GBM_API void gbm_stash_save(GbmSessionHandle session,
                            const char* message,
                            int32_t includeUntracked,
                            int32_t keepIndex,
                            const char* const* paths,
                            int32_t pathCount);

/// `git stash apply` (pop=0) or `git stash pop` (pop=1). Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED. The working copy is always
/// refreshed, even on a conflicting apply/pop (it still changed the work
/// tree); the stash list is refreshed only on success, matching pop's own
/// "does not drop on conflict" behavior.
GBM_API void gbm_stash_apply(GbmSessionHandle session, int32_t index, int32_t pop);

/// `git stash drop stash@{index}`. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success refreshes the
/// stash list.
GBM_API void gbm_stash_drop(GbmSessionHandle session, int32_t index);

/// `git stash branch`. Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED,
/// and on success refreshes the working copy, the stash list, and history
/// (this is also a checkout -- see StashBranchRequest's doc comment).
GBM_API void gbm_stash_branch(GbmSessionHandle session, int32_t index, const char* branchName);

/// `git stash show -p --include-untracked stash@{index}`. Async: fires
/// GBM_EVENT_STASH_DIFF_READY.
GBM_API void gbm_stash_request_diff(GbmSessionHandle session, int32_t index);

// --- Tags ----------------------------------------------------------------
// Tags themselves are read through gbm_refs_json() (RefKind::Tag); only the
// mutating side is here -- see src/core/git/ops/TagOps.h.

/// `git tag`, lightweight or annotated depending on whether `message` is
/// non-empty. `target` empty means HEAD. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success refreshes refs.
GBM_API void gbm_tag_create(GbmSessionHandle session,
                            const char* name,
                            const char* target,
                            const char* message,
                            int32_t force);

/// `git tag -d`, optionally followed by `git push <remoteName> --delete
/// <name>` when `alsoRemote` is set (routed through the same credential
/// prompt as gbm_remote_fetch() -- see GBM_EVENT_CREDENTIAL_REQUESTED).
/// Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success
/// refreshes refs.
GBM_API void gbm_tag_delete(GbmSessionHandle session,
                            const char* name,
                            int32_t alsoRemote,
                            const char* remoteName);

/// `git push <remoteName> <name>`, or every tag (`--tags`) when `name` is
/// empty. Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED.
GBM_API void gbm_tag_push(GbmSessionHandle session, const char* remoteName, const char* name);

// --- Worktrees -------------------------------------------------------------
// Mirrors RepositorySession's "M3: worktrees" section -- see
// src/core/git/ops/WorktreeOps.h.

/// Re-reads `git worktree list --porcelain`. Async: fires
/// GBM_EVENT_WORKTREES_UPDATED on success or GBM_EVENT_ERROR_OCCURRED on
/// failure.
GBM_API void gbm_worktree_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published worktree
/// list as a JSON array. Returns 0 on success, or a negative GbmErrorCode if
/// gbm_worktree_refresh() has not yet published one.
GBM_API int32_t gbm_worktrees_json(GbmSessionHandle session);

/// `git worktree add`. Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED,
/// and on success refreshes the worktree list.
GBM_API void gbm_worktree_add(GbmSessionHandle session,
                              const char* path,
                              const char* branch,
                              int32_t createBranch,
                              const char* newBranchName,
                              int32_t detach,
                              int32_t force);

GBM_API void gbm_worktree_remove(GbmSessionHandle session, const char* path, int32_t force);
GBM_API void gbm_worktree_prune(GbmSessionHandle session);
GBM_API void gbm_worktree_lock(GbmSessionHandle session, const char* path, const char* reason);
GBM_API void gbm_worktree_unlock(GbmSessionHandle session, const char* path);

// --- Remotes -----------------------------------------------------------
// Mirrors RepositorySession's "M3: remotes" section -- see
// src/core/git/ops/RemoteOps.h. Fetch/pull/push route credential prompts
// through GBM_EVENT_CREDENTIAL_REQUESTED /
// gbm_provide_credential()/gbm_cancel_credential() rather than failing
// outright the moment auth is needed (GIT_TERMINAL_PROMPT is always 0).

/// Re-reads `git remote -v`. Async: fires GBM_EVENT_REMOTES_UPDATED on
/// success or GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_remote_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published remote
/// list as a JSON array. Returns 0 on success, or a negative GbmErrorCode if
/// gbm_remote_refresh() has not yet published one.
GBM_API int32_t gbm_remotes_json(GbmSessionHandle session);

/// `git fetch`. `remoteName` empty fetches every remote (`--all`). `refs`
/// (with `refCount` entries) restricts the fetch to those specific refs
/// under `remoteName` (e.g. one branch, or every branch under a folder
/// prefix) instead of everything the remote's default refspec would bring
/// in -- `refCount` 0 fetches everything, the original behavior. A non-zero
/// `refCount` with an empty `remoteName` is rejected (see
/// GBM_EVENT_OPERATION_FINISHED's outcome): there is no well-defined "these
/// refs from every remote". Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success also triggers
/// the same refresh gbm_history_refresh() would (a fetch can bring in new
/// commits on remote-tracking refs).
GBM_API void gbm_remote_fetch(GbmSessionHandle session,
                              const char* remoteName,
                              const char* const* refs,
                              int32_t refCount,
                              int32_t prune,
                              int32_t tags);

/// `git pull` (merge, or `--rebase` when `rebase` is set). `remoteName`
/// empty uses the branch's configured upstream. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED; the working copy is always
/// refreshed, history only on success. A conflicting pull leaves the same
/// index state a conflicting merge/rebase would (see gbm_merge_branch()'s
/// doc comment).
GBM_API void gbm_pull(GbmSessionHandle session,
                      const char* remoteName,
                      const char* branch,
                      int32_t rebase,
                      int32_t stashFirst);

/// `git push`, with `--force-with-lease` when `forceWithLease` is set --
/// there is no plain `--force` in this app (see PushForceMode's doc
/// comment). `branch` empty pushes the current branch. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success also triggers
/// the same refresh gbm_history_refresh() would (the local remote-tracking
/// ref moves).
GBM_API void gbm_push(GbmSessionHandle session,
                      const char* remoteName,
                      const char* branch,
                      int32_t setUpstream,
                      int32_t pushTags,
                      int32_t forceWithLease);

/// `git remote prune <remoteName> --dry-run`: what a real prune (below)
/// would remove, without removing anything. Async: fires
/// GBM_EVENT_REMOTE_PRUNE_PREVIEW_READY, or GBM_EVENT_ERROR_OCCURRED on
/// failure (e.g. `remoteName` empty).
GBM_API void gbm_request_remote_prune_preview(GbmSessionHandle session, const char* remoteName);

/// Deletes exactly the remote-tracking refs in `refs` (typically a
/// user-edited subset of a prior gbm_request_remote_prune_preview() reply)
/// via `git branch --delete --remotes`, not `git remote prune`: the plain
/// command has no "delete only these" mode. Each entry is the short name a
/// preview reply returned, e.g. "origin/feature/old-branch". Async: fires
/// GBM_EVENT_OPERATION_FINISHED (same channel as branch delete, not
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED -- nothing here touches the
/// working tree or index, only remote-tracking refs), and on success also
/// triggers the same refresh gbm_history_refresh() would.
GBM_API void gbm_remote_prune(GbmSessionHandle session,
                              const char* remoteName,
                              const char* const* refs,
                              int32_t refCount);

/// `git remote add <name> <url>`. Async: fires GBM_EVENT_OPERATION_FINISHED
/// (same channel as gbm_remote_prune() -- adding a remote touches only repo
/// config, not the working tree or index), and on success also triggers the
/// same refresh gbm_remote_refresh() would.
GBM_API void gbm_remote_add(GbmSessionHandle session, const char* name, const char* url);

/// `git remote remove <name>`. Async: fires GBM_EVENT_OPERATION_FINISHED,
/// and on success also triggers the same refresh gbm_remote_refresh()
/// would.
GBM_API void gbm_remote_remove(GbmSessionHandle session, const char* name);

// --- Credential prompts (askpass) -------------------------------------
// Answers or dismisses whichever prompt GBM_EVENT_CREDENTIAL_REQUESTED most
// recently announced. A no-op if none is currently outstanding.

/// Answers the outstanding prompt. A `git` subprocess can ask more than once
/// per invocation (e.g. a password after a username), in which case
/// GBM_EVENT_CREDENTIAL_REQUESTED fires again for the follow-up prompt.
GBM_API void gbm_provide_credential(GbmSessionHandle session, const char* secret);

/// Dismisses the outstanding prompt; the blocked `git` subprocess fails
/// cleanly, exactly as if no credential helper were configured at all.
GBM_API void gbm_cancel_credential(GbmSessionHandle session);

// --- Blame / file history / line history / reflog / undo -----------------
// Mirrors RepositorySession's blame/file-history/line-history/reflog/undo
// section -- see src/core/git/{BlameStore,FileHistoryStore,ReflogStore}.h
// and src/core/git/ops/UndoOps.h. The first four are read-only, like
// gbm_working_copy_diff(); undo is the one mutation here.

/// Blames `path` as of `revision` (empty means the working tree).
/// `startLine`/`endLine` are 1-based and inclusive; either 0 blames the
/// whole file. Async: fires GBM_EVENT_BLAME_READY, or
/// GBM_EVENT_ERROR_OCCURRED on failure. A newer request for the same
/// session jumps ahead of any older, still-queued one (interactive
/// priority, like requesting a different file's diff while a slow one is
/// still loading).
GBM_API void gbm_request_blame(GbmSessionHandle session,
                               const char* path,
                               const char* revision,
                               int32_t startLine,
                               int32_t endLine);

/// Batch commit metadata (author/subject/body) for `oids`, e.g. the rows
/// currently visible in a scrolling commit list. Backed by a single
/// long-lived `git cat-file --batch` process rather than one `git show` per
/// oid -- see core/git/CommitMetaStore.h's doc comment. Async: always fires
/// GBM_EVENT_COMMIT_META_READY, never GBM_EVENT_ERROR_OCCURRED -- an
/// individual unreadable oid is simply missing from the reply array rather
/// than failing the whole batch (see CommitMetaStore::read()). Like
/// gbm_request_blame(), a newer request is not queued behind an older one.
GBM_API void gbm_request_commit_meta(GbmSessionHandle session,
                                     const char* const* oids,
                                     int32_t oidCount);

/// Commits that touched `path`, newest first, following renames the way
/// `git log --follow` does. `startRevision` empty means HEAD. Async: fires
/// GBM_EVENT_FILE_HISTORY_READY.
GBM_API void gbm_request_file_history(GbmSessionHandle session,
                                      const char* path,
                                      const char* startRevision);

/// Commits that touched lines `startLine..endLine` (1-based, inclusive) of
/// `path`, newest first. Async: fires GBM_EVENT_LINE_HISTORY_READY.
GBM_API void gbm_request_line_history(GbmSessionHandle session,
                                      const char* path,
                                      int32_t startLine,
                                      int32_t endLine,
                                      const char* startRevision);

/// `git reflog show <ref>`. `ref` empty means HEAD. Async: fires
/// GBM_EVENT_REFLOG_READY.
GBM_API void gbm_request_reflog(GbmSessionHandle session, const char* ref);

/// Populates the staging buffer with the current undo journal (most recent
/// last) as a JSON array -- one entry per operation submitted this
/// session, each `{"id", "description", "headBefore", "branchBefore",
/// "timestamp"}`. Synchronous; always returns 0. A snapshot taken right
/// after each operation's own outcome event, not a live read of
/// OperationRunner's journal -- see Session::undoJournal()'s doc comment
/// for why that matters.
GBM_API int32_t gbm_undo_journal_json(GbmSessionHandle session);

/// Reverses the most recent journal entry by hard-resetting back to where
/// HEAD stood before it ran. A no-op if the journal is empty. Refuses if
/// the checked-out branch has changed since (see UndoOps.h). Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success refreshes both
/// the working copy and history (HEAD moved).
GBM_API void gbm_undo_last(GbmSessionHandle session);

// --- Restore / clean -----------------------------------------------------
// Mirrors RepositorySession's "M4: reset / restore / clean" section -- see
// src/core/git/ops/ResetOps.h.

/// `git restore`. `staged` (--staged): resets the index from `source`
/// (default HEAD) without touching the work tree -- "unstage". Not staged:
/// overwrites the work tree from `source` (default the index) -- "discard
/// changes", destructive exactly like a hard reset of just these paths.
/// `source` empty uses the default for whichever mode `staged` selects.
/// Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success
/// refreshes the working copy.
GBM_API void gbm_restore_paths(GbmSessionHandle session,
                               const char* const* paths,
                               int32_t pathCount,
                               int32_t staged,
                               const char* source);

/// Read-only `git clean -n[x]`, so the caller can show exactly what would be
/// removed before committing to it. Async: fires
/// GBM_EVENT_CLEAN_PREVIEW_READY, or GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_clean_preview(GbmSessionHandle session, int32_t includeIgnored);

/// `git clean -fd[x]`. `paths`/`pathCount` empty means the whole work tree;
/// otherwise exactly these paths (what the caller left checked after
/// reviewing gbm_clean_preview()'s result). Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success refreshes the
/// working copy.
GBM_API void gbm_clean_untracked(GbmSessionHandle session,
                                 const char* const* paths,
                                 int32_t pathCount,
                                 int32_t includeIgnored);

// --- Rebase ----------------------------------------------------------------
// Mirrors RepositorySession's "M4: rebase" section -- see
// src/core/git/ops/RebaseOps.h.

/// Builds the todo list a plain `git rebase -i <upstream>` would start
/// from -- read-only, so the caller can show and let the user edit it
/// before anything runs. Async: fires GBM_EVENT_REBASE_PLAN_READY, or
/// GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_request_rebase_plan(GbmSessionHandle session, const char* upstream);

/// `git rebase -i`, with the todo list supplied by the caller instead of
/// through an interactive editor. `actions[i]` is a RebaseTodoEntry::Action
/// ordinal (0=Pick, 1=Edit, 2=Squash, 3=Fixup, 4=Drop, matching
/// RebaseOps.h); `oids[i]` is that entry's full commit hex (as returned by
/// gbm_request_rebase_plan(), reordered/dropped as the caller's UI allows);
/// `subjects[i]` is informational only (written into the todo file as a
/// comment, never parsed back). `onto` empty means onto `upstream` itself.
/// Async: fires GBM_EVENT_OPERATION_FINISHED; stops at the first conflict
/// or `edit` line exactly like `git rebase -i`, leaving the rest queued for
/// gbm_rebase_continue()/_skip()/_abort() -- the working copy is always
/// refreshed, history only on success.
GBM_API void gbm_rebase_interactive_start(GbmSessionHandle session,
                                          const char* upstream,
                                          const char* onto,
                                          const int32_t* actions,
                                          const char* const* oids,
                                          const char* const* subjects,
                                          int32_t entryCount,
                                          int32_t stashFirst);

/// Plain, non-interactive `git rebase`: replays every commit unchanged.
/// Same event/refresh contract as gbm_rebase_interactive_start().
GBM_API void gbm_rebase_start(GbmSessionHandle session,
                              const char* upstream,
                              const char* onto,
                              int32_t stashFirst);

GBM_API void gbm_rebase_continue(GbmSessionHandle session);
GBM_API void gbm_rebase_skip(GbmSessionHandle session);
GBM_API void gbm_rebase_abort(GbmSessionHandle session);

/// Same as gbm_rebase_continue(), except `message` overwrites
/// rebase-merge/message before continuing, so it becomes the resulting
/// commit's message instead of git's own proposal -- same
/// separate-function-not-added-parameter reasoning as
/// gbm_cherry_pick_continue_with_message(). Async: fires
/// GBM_EVENT_OPERATION_FINISHED, same as gbm_rebase_continue().
GBM_API void gbm_rebase_continue_with_message(GbmSessionHandle session, const char* message);

// --- Submodules ----------------------------------------------------------
// Mirrors RepositorySession's "M5: submodules" section -- see
// src/core/git/ops/SubmoduleOps.h. gbm_submodule_add()/_update() route
// credential prompts through GBM_EVENT_CREDENTIAL_REQUESTED like
// gbm_remote_fetch(), since both can clone/fetch over the network.

/// Re-reads `.gitmodules` + `git submodule status`. Async: fires
/// GBM_EVENT_SUBMODULES_UPDATED on success or GBM_EVENT_ERROR_OCCURRED on
/// failure.
GBM_API void gbm_submodule_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published submodule
/// list as a JSON array. Returns 0 on success, or a negative GbmErrorCode
/// if gbm_submodule_refresh() has not yet published one.
GBM_API int32_t gbm_submodules_json(GbmSessionHandle session);

/// `git submodule add [-b <branch>] <url> [<path>]`. `path` empty lets git
/// derive it from the URL. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success refreshes both
/// the working copy and the submodule list.
GBM_API void gbm_submodule_add(GbmSessionHandle session,
                               const char* url,
                               const char* path,
                               const char* branch);

/// `git submodule init [--] <paths...>`. `paths`/`pathCount` empty means
/// every submodule. Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED,
/// and on success refreshes the submodule list.
GBM_API void gbm_submodule_init(GbmSessionHandle session,
                                const char* const* paths,
                                int32_t pathCount,
                                int32_t recursive);

/// `git submodule update [--init] [--recursive] [--remote] [--] <paths...>`.
/// Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success
/// refreshes both the working copy and the submodule list.
GBM_API void gbm_submodule_update(GbmSessionHandle session,
                                  const char* const* paths,
                                  int32_t pathCount,
                                  int32_t recursive,
                                  int32_t init,
                                  int32_t remote);

/// `git submodule sync [--recursive] [--] <paths...>`.
GBM_API void gbm_submodule_sync(GbmSessionHandle session,
                                const char* const* paths,
                                int32_t pathCount,
                                int32_t recursive);

/// `git submodule deinit [-f] [--] <paths...>`.
GBM_API void gbm_submodule_deinit(GbmSessionHandle session,
                                  const char* const* paths,
                                  int32_t pathCount,
                                  int32_t force);

// --- Bisect ----------------------------------------------------------------
// Mirrors RepositorySession's "M5: bisect" section -- see
// src/core/git/ops/BisectOps.h.

/// Re-reads BISECT_LOG. Async: fires GBM_EVENT_BISECT_STATUS_UPDATED on
/// success or GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_bisect_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published
/// BisectStatus as JSON. Returns 0 on success, or a negative GbmErrorCode
/// if gbm_bisect_refresh() has not yet published one.
GBM_API int32_t gbm_bisect_status_json(GbmSessionHandle session);

/// `git bisect start [<bad> [<good>...]] [--] [<paths>...]`. `badRef` empty
/// together with an empty `goodRefs` is valid (waits for gbm_bisect_mark()
/// afterward). Async: fires GBM_EVENT_OPERATION_FINISHED, and on success
/// also refreshes both history (a bisect start checks out a commit) and the
/// bisect status.
GBM_API void gbm_bisect_start(GbmSessionHandle session,
                              const char* badRef,
                              const char* const* goodRefs,
                              int32_t goodCount,
                              const char* const* paths,
                              int32_t pathCount,
                              int32_t noCheckout);

/// `git bisect good|bad [<ref>]`. `ref` empty means HEAD. May conclude the
/// bisect, in which case OperationOutcome::summary carries git's own
/// "is the first bad commit" message verbatim. Async: fires
/// GBM_EVENT_OPERATION_FINISHED, and on success refreshes history and the
/// bisect status.
GBM_API void gbm_bisect_mark(GbmSessionHandle session, int32_t good, const char* ref);

/// `git bisect skip [<refs...>]`. Empty `refs`/`refCount` skips HEAD.
GBM_API void gbm_bisect_skip(GbmSessionHandle session, const char* const* refs, int32_t refCount);

/// `git bisect reset [<target>]`. `target` empty returns to whatever
/// gbm_bisect_start() was run from.
GBM_API void gbm_bisect_reset(GbmSessionHandle session, const char* target);

// --- LFS -------------------------------------------------------------------
// Mirrors RepositorySession's "M5: LFS" section -- see
// src/core/git/ops/LfsOps.h. gbm_lfs_pull()/_fetch() route credential
// prompts through GBM_EVENT_CREDENTIAL_REQUESTED like gbm_remote_fetch().

/// Detects `git-lfs` (once per session, cached) and re-reads tracked
/// patterns and file status. Async: fires GBM_EVENT_LFS_UPDATED on success
/// or GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_lfs_refresh(GbmSessionHandle session);

/// Populates the staging buffer with `{"available": bool, "version":
/// string}`. Returns 0 on success, or a negative GbmErrorCode if
/// gbm_lfs_refresh() has not yet run.
GBM_API int32_t gbm_lfs_installation_json(GbmSessionHandle session);

/// Populates the staging buffer with the tracked-pattern list as a JSON
/// array of strings.
GBM_API int32_t gbm_lfs_patterns_json(GbmSessionHandle session);

/// Populates the staging buffer with the tracked-file list as a JSON array.
GBM_API int32_t gbm_lfs_files_json(GbmSessionHandle session);

/// `git lfs install --local`. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success refreshes LFS
/// state.
GBM_API void gbm_lfs_install(GbmSessionHandle session);

/// `git lfs track "<pattern>"`. Editing `.gitattributes` further (staging,
/// committing) is left to the caller.
GBM_API void gbm_lfs_track(GbmSessionHandle session, const char* pattern);

/// `git lfs untrack "<pattern>"`.
GBM_API void gbm_lfs_untrack(GbmSessionHandle session, const char* pattern);

/// `git lfs pull [<remote>]`. `remoteName` empty uses the default remote.
/// Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success
/// refreshes both the working copy (objects are checked out) and LFS state.
GBM_API void gbm_lfs_pull(GbmSessionHandle session, const char* remoteName);

/// `git lfs fetch [<remote>]`: downloads objects without touching the work
/// tree. Same event contract as gbm_lfs_pull(), refreshing LFS state only.
GBM_API void gbm_lfs_fetch(GbmSessionHandle session, const char* remoteName);

/// `git lfs prune [--dry-run]`.
GBM_API void gbm_lfs_prune(GbmSessionHandle session, int32_t dryRun);

// --- Patch import/export ---------------------------------------------------
// Mirrors RepositorySession's "M5: patch import/export" section -- see
// src/core/git/ops/PatchOps.h.

/// `git format-patch -1 <commit> --start-number <n> -o <dir>`, once per
/// commit in `commitHexes` (oldest first, same convention as
/// gbm_cherry_pick()). Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED; nothing in the repository
/// changes, so no further refresh follows.
GBM_API void gbm_patch_export(GbmSessionHandle session,
                              const char* const* commitHexes,
                              int32_t commitCount,
                              const char* outputDir);

// --- File at revision -------------------------------------------------------
// Backs context menu 05-K's "Open file at this revision" / "Save this
// revision as..." -- see src/core/git/ops/BlobOps.h.

/// `git cat-file blob <revision>:<path>`, written verbatim to `destPath`.
///
/// Writes bytes to a path rather than returning the content inline (the way
/// gbm_request_working_tree_content() does) because both callers need a real
/// file: one hands `destPath` to the OS file association, the other is a
/// "save as". A JSON string payload could not carry a binary blob at all,
/// and an image recovered out of history is exactly the case this exists
/// for.
///
/// `revision` is any expression git accepts (`<oid>`, `HEAD~2`, a branch or
/// tag name); `path` is repository-relative and forward-slashed, as the
/// changed-files list reports it. Nothing is written unless the read
/// succeeded, so a failure never leaves a truncated file behind. Async:
/// fires GBM_EVENT_FILE_AT_REVISION_EXPORTED, with `succeeded` false and an
/// `error` on any failure -- including a path that does not exist at that
/// revision, which is an ordinary outcome when the user right-clicks a file
/// in a commit that deleted it.
GBM_API void gbm_export_file_at_revision(GbmSessionHandle session,
                                         const char* revision,
                                         const char* path,
                                         const char* destPath);

/// `git apply`: applies a plain diff without creating a commit.
/// `threeWay` falls back to a merge (leaving conflict markers) instead of
/// refusing outright when the patch does not apply cleanly; `updateIndex`
/// also stages the result. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success refreshes the
/// working copy.
GBM_API void gbm_patch_apply_files(GbmSessionHandle session,
                                   const char* const* patchFiles,
                                   int32_t fileCount,
                                   int32_t threeWay,
                                   int32_t updateIndex);

/// `git am`: applies one or more `format-patch`-style patches as commits,
/// preserving author/date/message. Async: fires
/// GBM_EVENT_OPERATION_FINISHED; a patch that does not apply stops the
/// sequence exactly like gbm_cherry_pick(), leaving the rest queued for
/// gbm_patch_import_continue()/_skip()/_abort().
GBM_API void gbm_patch_import(GbmSessionHandle session,
                              const char* const* patchFiles,
                              int32_t fileCount,
                              int32_t threeWay);

GBM_API void gbm_patch_import_continue(GbmSessionHandle session);
GBM_API void gbm_patch_import_skip(GbmSessionHandle session);
GBM_API void gbm_patch_import_abort(GbmSessionHandle session);

// --- Local Git identity / commit-graph maintenance -------------------------
// Mirrors RepositorySession's "Phase 6: per-repository Git identity
// override" and "Commit-graph maintenance" sections -- see
// src/core/git/ops/ConfigOps.h and src/core/git/ops/MaintenanceOps.h. The
// commit-graph *advice* preference (whether the user has already been
// asked, or declined) has no git-level meaning -- it is a pure UI setting,
// persisted client-side (see the Flutter side's own local storage), not
// part of this surface.

/// Re-reads `user.name`/`user.email` scoped `--local` to this repository.
/// Async: fires GBM_EVENT_LOCAL_IDENTITY_UPDATED on success or
/// GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_local_identity_refresh(GbmSessionHandle session);

/// Populates the staging buffer with `{"name": string, "email": string,
/// "overridden": bool}`. Returns 0 on success, or a negative GbmErrorCode
/// if gbm_local_identity_refresh() has not yet published one.
GBM_API int32_t gbm_local_identity_json(GbmSessionHandle session);

/// Re-reads whichever `user.name`/`user.email` git itself would attribute a
/// new commit here (local override falling back to global/system config).
/// Async: fires GBM_EVENT_EFFECTIVE_IDENTITY_UPDATED.
GBM_API void gbm_effective_identity_refresh(GbmSessionHandle session);

/// Populates the staging buffer with `{"name": string, "email": string}`.
/// Returns 0 on success, or a negative GbmErrorCode if
/// gbm_effective_identity_refresh() has not yet published one.
GBM_API int32_t gbm_effective_identity_json(GbmSessionHandle session);

/// `git config --local user.name <name>` then `user.email <email>`. Async:
/// fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success
/// refreshes both the local and effective identity.
GBM_API void gbm_set_local_identity(GbmSessionHandle session, const char* name, const char* email);

/// `git config --local --unset user.name`/`user.email`, best-effort (an
/// already-unset key is not treated as a failure). Same event/refresh
/// contract as gbm_set_local_identity().
GBM_API void gbm_clear_local_identity(GbmSessionHandle session);

/// Filesystem check only, no subprocess -- whether a commit-graph file
/// already exists for this repository. Synchronous; returns 1 if present,
/// 0 otherwise.
GBM_API int32_t gbm_has_commit_graph(GbmSessionHandle session);

/// `git commit-graph write --reachable [--changed-paths] [--split]`, with
/// `--split`/`--changed-paths` gated on this git installation's detected
/// capabilities exactly like RepositorySession::writeCommitGraph(). Async:
/// fires GBM_EVENT_COMMIT_GRAPH_WRITE_FINISHED; unlike every other
/// mutation here, does not itself trigger a history refresh (the commits
/// are unchanged -- see the doc comment on the mirrored Qt method).
GBM_API void gbm_write_commit_graph(GbmSessionHandle session);

// --- Repository creation (init / clone) -------------------------------------
// Session-less, like Discovery below: these create the repository directory
// itself, so they run before any GbmSessionHandle exists. On success, the
// caller opens a normal session on the resulting working directory via
// gbm_session_open() -- neither function opens or returns a session itself.

/// Runs `git init <path>` synchronously (blocks the calling thread -- init
/// is local and fast, so this is safe to call directly, unlike clone below).
/// `path` is created if it doesn't already exist. Returns 0 on success, or a
/// negative GbmErrorCode with the staging buffer populated with a GitError
/// JSON.
GBM_API int32_t gbm_repo_init(const char* path);

/// Runs `git clone <url> <destPath>` synchronously (blocks the calling
/// thread -- callers should run this off the UI isolate, e.g. via Dart's
/// Isolate.run, the same caveat gbm_discovery_scan_all() carries, now
/// extended to a network operation with no upper bound on how long it may
/// run). Per-object transfer progress is not reported -- see
/// InitCloneOps.h's doc comment. Returns 0 on success, or a negative
/// GbmErrorCode with the staging buffer populated with a GitError JSON.
GBM_API int32_t gbm_repo_clone(const char* url, const char* destPath);

// --- Discovery -------------------------------------------------------------
// A separate handle class from GbmSessionHandle: discovery scans base
// folders and is not tied to any one open repository -- see
// src/core/cache/RepoIndexDb.h / src/core/discovery/Scanner.h.

/// Opens (creating and migrating if needed) the repo index database at
/// `dbPath`, or an in-memory database when `dbPath` is empty. Returns null
/// and populates the staging buffer with a GitError JSON on failure.
GBM_API GbmDiscoveryHandle gbm_discovery_open(const char* dbPath);

GBM_API void gbm_discovery_close(GbmDiscoveryHandle discovery);

/// Registers a folder to scan. Returns the new base folder's row id (>= 0),
/// or a negative GbmErrorCode on failure.
GBM_API int64_t gbm_discovery_add_base_folder(GbmDiscoveryHandle discovery,
                                              const char* path,
                                              int32_t maxDepth,
                                              int32_t followLinks);

/// Scans every enabled base folder synchronously (blocks the calling
/// thread -- callers should run this off the UI isolate, e.g. via Dart's
/// Isolate.run). Returns 0 on success (even if some folders had nothing new)
/// or a negative GbmErrorCode.
GBM_API int32_t gbm_discovery_scan_all(GbmDiscoveryHandle discovery);

/// Populates the staging buffer with every known repository (including
/// those currently missing) as a JSON array. Returns 0 on success.
GBM_API int32_t gbm_discovery_list_repos_json(GbmDiscoveryHandle discovery);

/// Populates the staging buffer with every registered base folder as a JSON
/// array (id/path/enabled/maxDepth/followLinks/lastScan*). Returns 0 on
/// success.
GBM_API int32_t gbm_discovery_base_folders_json(GbmDiscoveryHandle discovery);

/// Unregisters a base folder (its already-discovered repositories stay in
/// the index, matching RepoIndexDb::removeBaseFolder's own contract).
/// Returns 0 on success, or a negative GbmErrorCode.
GBM_API int32_t gbm_discovery_remove_base_folder(GbmDiscoveryHandle discovery,
                                                 int64_t baseFolderId);

/// Enables/disables a base folder without removing it -- a disabled folder
/// is skipped by gbm_discovery_scan_all() but its known repositories stay
/// listed. Returns 0 on success, or a negative GbmErrorCode.
GBM_API int32_t gbm_discovery_set_base_folder_enabled(GbmDiscoveryHandle discovery,
                                                      int64_t baseFolderId,
                                                      int32_t enabled);

/// Changes how many levels below a base folder are scanned. Also clears its
/// stored directory signatures (see RepoIndexDb::setBaseFolderMaxDepth's doc
/// comment) -- a signature recorded "nothing below here" under the old depth
/// would otherwise wrongly prune a subtree a deeper scan should now visit.
/// Returns 0 on success, or a negative GbmErrorCode.
GBM_API int32_t gbm_discovery_set_base_folder_depth(GbmDiscoveryHandle discovery,
                                                    int64_t baseFolderId,
                                                    int32_t maxDepth);
