// The public C ABI for the Flutter UI. This is the only header the Dart FFI
// bindings (app_flutter/lib/data/ffi/gbm_bindings.dart, generated by ffigen)
// are generated from, and the only header anything outside src/capi should
// include. Everything here is extern "C": no C++ types cross this boundary.
//
// Two data-marshalling conventions are used, matching the plan's "JSON for
// structured/low-frequency data, packed binary for the graph" split:
//
//  * Scalar calls (checkout, ...) take plain C parameters and return an
//    int32_t status: 0 or positive on success, a negative value that is the
//    negated ordinal of gbm::GitError::Code on failure (0 = Unknown, -1 =
//    Unknown, i.e. negate-then-subtract-one avoided: see GBM_ERR below).
//  * Structured snapshots (repo state, discovered repos) are returned as
//    JSON through a thread-local staging buffer: call the function that
//    produces the result, then gbm_last_result_json_len() and
//    gbm_last_result_json_copy() immediately after, on the same thread.
//  * The commit graph is exposed as packed binary buffers
//    (gbm_graph_snapshot_*) whose layout matches gbm::GraphSnapshot exactly
//    -- see src/core/graph/GraphSnapshot.h. These are zero-copy views valid
//    until the next gbm_graph_snapshot_rows() call for the same session or
//    an explicit gbm_graph_snapshot_release().
//  * Asynchronous results (history refresh, checkout) are delivered through
//    a per-session event callback registered with gbm_register_callback().
//    The callback may be invoked from any native thread -- a ThreadPool
//    worker or the operation runner's serial thread -- never from the
//    thread that called gbm_register_callback(). On the Dart side this is
//    exactly what NativeCallable.listener is for. A non-empty payload is
//    heap-allocated by this library and MUST be released by calling
//    gbm_free_event_payload() once the receiver is done reading it.

#pragma once

#include <stdint.h>

#if defined(_WIN32)
#define GBM_API extern "C" __declspec(dllexport)
#else
#define GBM_API extern "C" __attribute__((visibility("default")))
#endif

// --- Handles -----------------------------------------------------------

typedef void* GbmSessionHandle;
typedef void* GbmDiscoveryHandle;

// --- Errors --------------------------------------------------------------
// Mirrors gbm::GitError::Code (src/core/base/Error.h) 1:1. A scalar call
// returns 0 on success and -(1 + code-ordinal) on failure, so GBM_ERR_UNKNOWN
// (ordinal 0) maps to -1 and 0 stays unambiguously "success".

enum GbmErrorCode {
    GBM_ERR_UNKNOWN = 0,
    GBM_ERR_NOT_FOUND = 1,
    GBM_ERR_INVALID_ARGUMENT = 2,
    GBM_ERR_CONFLICT = 3,
    GBM_ERR_LOCK_HELD = 4,
    GBM_ERR_AUTH = 5,
    GBM_ERR_HOST_KEY = 6,
    GBM_ERR_NON_FAST_FORWARD = 7,
    GBM_ERR_DIRTY_WORK_TREE = 8,
    GBM_ERR_HOOK_REJECTED = 9,
    GBM_ERR_CANCELLED = 10,
    GBM_ERR_PROCESS_FAILED = 11,
    GBM_ERR_SPAWN_FAILED = 12,
    GBM_ERR_PARSE_ERROR = 13,
    GBM_ERR_CORRUPT = 14,
    GBM_ERR_UNSUPPORTED = 15,
    GBM_ERR_TIMEOUT = 16,
    GBM_ERR_TOO_LARGE = 17,
    GBM_ERR_DATABASE = 18,
    GBM_ERR_IO = 19,
};

// --- Events ----------------------------------------------------------------
// One ordinal per RepositorySession Qt signal this bridge replaces (see
// src/app/bridge/RepositorySession.h:505-598). Only the M0/M1 subset is
// defined so far; later milestones extend this enum, never renumber it.

enum GbmEventType {
    GBM_EVENT_GRAPH_UPDATED = 0,       ///< payload: {"complete": bool}
    GBM_EVENT_REFS_UPDATED = 1,        ///< no payload
    GBM_EVENT_ERROR_OCCURRED = 2,      ///< payload: GitError JSON
    GBM_EVENT_OPERATION_FINISHED = 3,  ///< payload: OperationOutcome JSON

    /// no payload; read the new status with gbm_working_copy_status_json().
    GBM_EVENT_WORKING_COPY_STATUS_UPDATED = 4,
    /// payload: OperationOutcome JSON. Fired by stage/unstage/commit.
    GBM_EVENT_WORKING_COPY_OPERATION_FINISHED = 5,
    /// payload: {"path": string, "staged": bool, "diff": ParsedDiff JSON}.
    /// Reply to gbm_working_copy_diff_json(); the echoed path/staged let a
    /// caller that issued several diff requests match replies back up.
    GBM_EVENT_WORKING_COPY_DIFF_READY = 6,

    /// no payload; read the new list with gbm_stashes_json().
    GBM_EVENT_STASHES_UPDATED = 7,
    /// payload: {"index": int, "diff": ParsedDiff JSON}. Reply to
    /// gbm_stash_request_diff().
    GBM_EVENT_STASH_DIFF_READY = 8,
    /// no payload; read the new list with gbm_worktrees_json().
    GBM_EVENT_WORKTREES_UPDATED = 9,
    /// no payload; read the new list with gbm_remotes_json().
    GBM_EVENT_REMOTES_UPDATED = 10,
    /// payload: {"prompt": string}. A `git` subprocess spawned by a
    /// fetch/pull/push/remote-tag-delete is blocked waiting for a username
    /// or password -- reply with gbm_provide_credential() or
    /// gbm_cancel_credential(). See gbm_provide_credential()'s doc comment
    /// for why a follow-up prompt in the same operation fires this again.
    GBM_EVENT_CREDENTIAL_REQUESTED = 11,
    /// payload: OperationRecord JSON. Fired once per `git` invocation this
    /// session makes, for an operation-log panel -- see
    /// core/base/Logging.h's OperationRecord doc comment. Distinct from
    /// every other event: it can fire during a *read* (history refresh,
    /// working-copy refresh), not only a mutation.
    GBM_EVENT_OPERATION_LOG_RECORD = 12,
};

typedef void (*GbmEventCallback)(GbmSessionHandle session,
                                  int32_t eventType,
                                  const uint8_t* payload,
                                  int32_t payloadLen,
                                  void* userData);

/// Frees a payload buffer handed to a GbmEventCallback. Safe to call only
/// once per payload, and only after the callback that received it has
/// finished reading it. A null or already-freed pointer is not accepted.
GBM_API void gbm_free_event_payload(const uint8_t* payload);

// --- Thread-local synchronous-result staging buffer -------------------------
// Populated by any function documented "populates the staging buffer".
// Always drain it (len, then copy) on the same thread and before the next
// such call on that thread -- it is thread-local, not per-session.

GBM_API int32_t gbm_last_result_json_len(void);
GBM_API void gbm_last_result_json_copy(uint8_t* out, int32_t outLen);

// --- Session lifecycle -------------------------------------------------

/// Opens a repository. `commonDir` may be empty (defaults to gitDir) for a
/// non-worktree repository. Detects the git executable fresh each call is
/// avoided: detection is cached process-wide after the first successful
/// open. Returns null and populates the staging buffer with a GitError JSON
/// on failure (e.g. no usable git on PATH).
GBM_API GbmSessionHandle gbm_session_open(const char* workDir,
                                          const char* gitDir,
                                          const char* commonDir);

/// Cancels any in-flight work and releases the session. `session` must not
/// be used again afterwards.
GBM_API void gbm_session_close(GbmSessionHandle session);

/// Registers the event callback for this session. Replaces any previously
/// registered callback. Must be called before any async-producing call
/// (gbm_history_refresh, gbm_branch_checkout) if events are to be observed.
GBM_API void gbm_register_callback(GbmSessionHandle session,
                                   GbmEventCallback callback,
                                   void* userData);

// --- Repository state --------------------------------------------------

/// Populates the staging buffer with the current RepoState as JSON.
/// Returns 0 on success.
GBM_API int32_t gbm_repo_state_json(GbmSessionHandle session);

// --- History / graph -----------------------------------------------------

/// Requests a refs + history refresh. Runs on a shared background worker;
/// never blocks the calling thread. Fires GBM_EVENT_REFS_UPDATED once refs
/// are read, then one or more GBM_EVENT_GRAPH_UPDATED as the walk streams
/// (the last has payload {"complete": true}), or GBM_EVENT_ERROR_OCCURRED on
/// failure.
GBM_API void gbm_history_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published RefSnapshot
/// (branches, tags, HEAD) as JSON. Returns 0 on success, or a negative
/// GbmErrorCode if gbm_history_refresh() has not yet published one.
GBM_API int32_t gbm_refs_json(GbmSessionHandle session);

/// Row-parallel packed GraphSnapshot::RowMeta buffer (16 bytes/row, see
/// src/core/graph/GraphSnapshot.h). Pins the underlying snapshot until the
/// next call to this function for the same session or
/// gbm_graph_snapshot_release(). Null with *rowCount == 0 if no snapshot has
/// been published yet.
GBM_API const uint8_t* gbm_graph_snapshot_rows(GbmSessionHandle session,
                                               int32_t* rowCount,
                                               int32_t* rowStride);

/// Packed ObjectId buffer, one 33-byte entry per row, same row order and
/// pinning as gbm_graph_snapshot_rows().
GBM_API const uint8_t* gbm_graph_snapshot_oids(GbmSessionHandle session,
                                               int32_t* oidCount,
                                               int32_t* oidStride);

/// Packed RowId (uint32) parent-pool buffer; see RowMeta::parentOffset.
GBM_API const uint32_t* gbm_graph_snapshot_parents(GbmSessionHandle session,
                                                    int32_t* parentCount);

/// Packed GraphSnapshot::Edge buffer (16 bytes/edge).
GBM_API const uint8_t* gbm_graph_snapshot_edges(GbmSessionHandle session,
                                                int32_t* edgeCount,
                                                int32_t* edgeStride);

GBM_API int32_t gbm_graph_snapshot_lane_count(GbmSessionHandle session);
GBM_API int32_t gbm_graph_snapshot_complete(GbmSessionHandle session);
GBM_API int32_t gbm_graph_snapshot_truncated(GbmSessionHandle session);

/// Releases the pinned snapshot from the last gbm_graph_snapshot_rows() call.
/// Safe to call even if nothing is pinned.
GBM_API void gbm_graph_snapshot_release(GbmSessionHandle session);

// --- Branches ------------------------------------------------------------

/// `git switch`/`git checkout`. Async: fires GBM_EVENT_OPERATION_FINISHED
/// with an OperationOutcome JSON payload, and on success also triggers the
/// same refresh gbm_history_refresh() would (so REFS_UPDATED/GRAPH_UPDATED
/// follow). String parameters must be UTF-8 and non-null (pass "" for
/// absent); boolean parameters are 0/1.
GBM_API void gbm_branch_checkout(GbmSessionHandle session,
                                 const char* target,
                                 int32_t detach,
                                 int32_t createBranch,
                                 const char* newBranchName,
                                 int32_t force,
                                 int32_t stashFirst,
                                 int32_t recurseSubmodules);

// --- Reset -----------------------------------------------------------------
// Mirrors RepositorySession::resetTo -- see src/core/git/ops/ResetOps.h.

/// `mode`: 0 = soft, 1 = mixed, 2 = hard (ResetMode's ordinal order in
/// ResetOps.h: Soft, Mixed, Hard). `target` empty means HEAD. Async: fires
/// GBM_EVENT_OPERATION_FINISHED, and on success also triggers both a
/// history refresh (HEAD moved) and a working-copy refresh (mixed/hard
/// rewrite the index and/or work tree).
GBM_API void gbm_reset_to(GbmSessionHandle session, const char* target, int32_t mode);

// --- Merge -------------------------------------------------------------
// Mirrors RepositorySession::mergeBranch/abortMerge -- see
// src/core/git/ops/MergeOps.h.

/// `mode`: 0 = fast-forward-only, 1 = no-fast-forward, 2 = squash
/// (MergeMode's ordinal order: FastForwardOnly, NoFastForward, Squash).
/// `message` overrides the default merge commit message (ignored for
/// squash); pass "" to use git's default. Async: fires
/// GBM_EVENT_OPERATION_FINISHED. A conflicting merge is reported with
/// `succeeded: false` and `error.code` == GBM_ERR_CONFLICT, exactly like any
/// other outcome -- it is not a crash or an exceptional case, see
/// MergeOps.h's doc comment. Either way the working copy is refreshed so
/// conflicted paths show up; history is refreshed only on success.
GBM_API void gbm_merge_branch(GbmSessionHandle session,
                              const char* target,
                              int32_t mode,
                              const char* message,
                              int32_t stashFirst);

/// `git merge --abort`. Async: fires GBM_EVENT_OPERATION_FINISHED.
GBM_API void gbm_merge_abort(GbmSessionHandle session);

// --- Cherry-pick -----------------------------------------------------------
// Mirrors RepositorySession::cherryPick/continueCherryPick/skipCherryPick/
// abortCherryPick -- see src/core/git/ops/CherryPickOps.h.

/// `commitHexes`/`commitCount`: full or abbreviated hex object ids, oldest
/// first (the order they are applied in). `mainline` is 1-based, 0 means
/// "not a merge commit". Async: fires GBM_EVENT_OPERATION_FINISHED; stops at
/// the first conflict exactly like `git cherry-pick`, leaving the remaining
/// commits queued for gbm_cherry_pick_continue()/_skip()/_abort().
GBM_API void gbm_cherry_pick(GbmSessionHandle session,
                             const char* const* commitHexes,
                             int32_t commitCount,
                             int32_t mainline,
                             int32_t noCommit,
                             int32_t stashFirst);

GBM_API void gbm_cherry_pick_continue(GbmSessionHandle session);
GBM_API void gbm_cherry_pick_skip(GbmSessionHandle session);
GBM_API void gbm_cherry_pick_abort(GbmSessionHandle session);

// --- Revert ------------------------------------------------------------
// Mirrors RepositorySession::revertCommit -- see src/core/git/ops/RevertOps.h.

/// Same `commitHexes`/`commitCount` convention as gbm_cherry_pick(). Async:
/// fires GBM_EVENT_OPERATION_FINISHED. No continue/skip/abort entry point --
/// see RevertOps.h's doc comment for why.
GBM_API void gbm_revert(GbmSessionHandle session,
                        const char* const* commitHexes,
                        int32_t commitCount,
                        int32_t noCommit,
                        int32_t stashFirst);

// --- Conflict resolution -----------------------------------------------
// Mirrors RepositorySession::resolveConflict -- see
// src/core/git/ops/ConflictOps.h.

/// `resolution`: 0 = take ours, 1 = take theirs, 2 = mark resolved (stage
/// current on-disk content as-is), 3 = write resolved (write
/// `resolvedContent` to `path` first, then stage it) -- ConflictResolution's
/// ordinal order in ConflictOps.h. `oursBlobMissing`/`theirsBlobMissing`
/// matter only for take-ours/take-theirs (see WorkingCopyEntry::oursBlob/
/// theirsBlob's doc comments); `resolvedContent` matters only for
/// write-resolved and must be non-empty then. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED (this is a working-copy-scoped
/// fix, not a top-level branch operation), and refreshes the working copy
/// on success.
GBM_API void gbm_resolve_conflict(GbmSessionHandle session,
                                  const char* path,
                                  int32_t resolution,
                                  int32_t oursBlobMissing,
                                  int32_t theirsBlobMissing,
                                  const char* resolvedContent);

// --- Working copy / diff ---------------------------------------------------
// Mirrors RepositorySession's working-copy methods (RepositorySession.h,
// "Working Copy" section) and DiffService's workingTreeDiff -- see
// src/core/git/WorkingCopyStatus.h and src/core/git/DiffService.h.

/// Re-reads `git status`. Deliberately uncached (see WorkingCopyStatusReader's
/// doc comment: the work tree changes on every keystroke), so this always
/// runs a fresh scan. Async: fires GBM_EVENT_WORKING_COPY_STATUS_UPDATED on
/// success or GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_working_copy_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published
/// WorkingCopyStatus as JSON. Returns 0 on success, or a negative
/// GbmErrorCode if gbm_working_copy_refresh() has not yet published one.
GBM_API int32_t gbm_working_copy_status_json(GbmSessionHandle session);

/// Diff of one path: work tree vs index (staged=0) or index vs HEAD
/// (staged=1). Async: fires GBM_EVENT_WORKING_COPY_DIFF_READY.
GBM_API void gbm_working_copy_diff(GbmSessionHandle session, const char* path, int32_t staged);

/// `git add -- <paths>`. `paths`/`pathCount` describe a plain C array of
/// UTF-8 C strings. Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED,
/// and on success also triggers gbm_working_copy_refresh().
GBM_API void gbm_stage_files(GbmSessionHandle session, const char* const* paths, int32_t pathCount);

/// `git restore --staged -- <paths>`. Same event/refresh contract as
/// gbm_stage_files().
GBM_API void gbm_unstage_files(GbmSessionHandle session, const char* const* paths, int32_t pathCount);

/// `git commit` / `git commit --amend`. `message` empty together with
/// `amend` keeps the existing message (`--amend --no-edit`); empty otherwise
/// is rejected before git runs. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success also triggers
/// both gbm_working_copy_refresh() and the same refresh
/// gbm_history_refresh() would (the new commit needs to appear in the
/// graph).
GBM_API void gbm_commit_changes(GbmSessionHandle session,
                                const char* message,
                                int32_t amend,
                                int32_t signOff);

// --- Stashes -----------------------------------------------------------
// Mirrors RepositorySession's "M3: stashes" section -- see
// src/core/git/ops/StashOps.h.

/// Re-reads `git stash list`. Async: fires GBM_EVENT_STASHES_UPDATED on
/// success or GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_stash_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published stash list
/// as a JSON array. Returns 0 on success, or a negative GbmErrorCode if
/// gbm_stash_refresh() has not yet published one.
GBM_API int32_t gbm_stashes_json(GbmSessionHandle session);

/// `git stash push`. `paths`/`pathCount` restrict the stash to those paths,
/// like gbm_stage_files(); an empty array stashes every changed path. Async:
/// fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success also
/// refreshes both the working copy and the stash list.
GBM_API void gbm_stash_save(GbmSessionHandle session,
                            const char* message,
                            int32_t includeUntracked,
                            int32_t keepIndex,
                            const char* const* paths,
                            int32_t pathCount);

/// `git stash apply` (pop=0) or `git stash pop` (pop=1). Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED. The working copy is always
/// refreshed, even on a conflicting apply/pop (it still changed the work
/// tree); the stash list is refreshed only on success, matching pop's own
/// "does not drop on conflict" behavior.
GBM_API void gbm_stash_apply(GbmSessionHandle session, int32_t index, int32_t pop);

/// `git stash drop stash@{index}`. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success refreshes the
/// stash list.
GBM_API void gbm_stash_drop(GbmSessionHandle session, int32_t index);

/// `git stash branch`. Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED,
/// and on success refreshes the working copy, the stash list, and history
/// (this is also a checkout -- see StashBranchRequest's doc comment).
GBM_API void gbm_stash_branch(GbmSessionHandle session, int32_t index, const char* branchName);

/// `git stash show -p --include-untracked stash@{index}`. Async: fires
/// GBM_EVENT_STASH_DIFF_READY.
GBM_API void gbm_stash_request_diff(GbmSessionHandle session, int32_t index);

// --- Tags ----------------------------------------------------------------
// Tags themselves are read through gbm_refs_json() (RefKind::Tag); only the
// mutating side is here -- see src/core/git/ops/TagOps.h.

/// `git tag`, lightweight or annotated depending on whether `message` is
/// non-empty. `target` empty means HEAD. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success refreshes refs.
GBM_API void gbm_tag_create(GbmSessionHandle session,
                            const char* name,
                            const char* target,
                            const char* message,
                            int32_t force);

/// `git tag -d`, optionally followed by `git push <remoteName> --delete
/// <name>` when `alsoRemote` is set (routed through the same credential
/// prompt as gbm_remote_fetch() -- see GBM_EVENT_CREDENTIAL_REQUESTED).
/// Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success
/// refreshes refs.
GBM_API void gbm_tag_delete(GbmSessionHandle session, const char* name, int32_t alsoRemote, const char* remoteName);

/// `git push <remoteName> <name>`, or every tag (`--tags`) when `name` is
/// empty. Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED.
GBM_API void gbm_tag_push(GbmSessionHandle session, const char* remoteName, const char* name);

// --- Worktrees -------------------------------------------------------------
// Mirrors RepositorySession's "M3: worktrees" section -- see
// src/core/git/ops/WorktreeOps.h.

/// Re-reads `git worktree list --porcelain`. Async: fires
/// GBM_EVENT_WORKTREES_UPDATED on success or GBM_EVENT_ERROR_OCCURRED on
/// failure.
GBM_API void gbm_worktree_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published worktree
/// list as a JSON array. Returns 0 on success, or a negative GbmErrorCode if
/// gbm_worktree_refresh() has not yet published one.
GBM_API int32_t gbm_worktrees_json(GbmSessionHandle session);

/// `git worktree add`. Async: fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED,
/// and on success refreshes the worktree list.
GBM_API void gbm_worktree_add(GbmSessionHandle session,
                              const char* path,
                              const char* branch,
                              int32_t createBranch,
                              const char* newBranchName,
                              int32_t detach,
                              int32_t force);

GBM_API void gbm_worktree_remove(GbmSessionHandle session, const char* path, int32_t force);
GBM_API void gbm_worktree_prune(GbmSessionHandle session);
GBM_API void gbm_worktree_lock(GbmSessionHandle session, const char* path, const char* reason);
GBM_API void gbm_worktree_unlock(GbmSessionHandle session, const char* path);

// --- Remotes -----------------------------------------------------------
// Mirrors RepositorySession's "M3: remotes" section -- see
// src/core/git/ops/RemoteOps.h. Fetch/pull/push route credential prompts
// through GBM_EVENT_CREDENTIAL_REQUESTED /
// gbm_provide_credential()/gbm_cancel_credential() rather than failing
// outright the moment auth is needed (GIT_TERMINAL_PROMPT is always 0).

/// Re-reads `git remote -v`. Async: fires GBM_EVENT_REMOTES_UPDATED on
/// success or GBM_EVENT_ERROR_OCCURRED on failure.
GBM_API void gbm_remote_refresh(GbmSessionHandle session);

/// Populates the staging buffer with the most recently published remote
/// list as a JSON array. Returns 0 on success, or a negative GbmErrorCode if
/// gbm_remote_refresh() has not yet published one.
GBM_API int32_t gbm_remotes_json(GbmSessionHandle session);

/// `git fetch`. `remoteName` empty fetches every remote (`--all`). Async:
/// fires GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success also
/// triggers the same refresh gbm_history_refresh() would (a fetch can bring
/// in new commits on remote-tracking refs).
GBM_API void gbm_remote_fetch(GbmSessionHandle session, const char* remoteName, int32_t prune, int32_t tags);

/// `git pull` (merge, or `--rebase` when `rebase` is set). `remoteName`
/// empty uses the branch's configured upstream. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED; the working copy is always
/// refreshed, history only on success. A conflicting pull leaves the same
/// index state a conflicting merge/rebase would (see gbm_merge_branch()'s
/// doc comment).
GBM_API void gbm_pull(GbmSessionHandle session,
                      const char* remoteName,
                      const char* branch,
                      int32_t rebase,
                      int32_t stashFirst);

/// `git push`, with `--force-with-lease` when `forceWithLease` is set --
/// there is no plain `--force` in this app (see PushForceMode's doc
/// comment). `branch` empty pushes the current branch. Async: fires
/// GBM_EVENT_WORKING_COPY_OPERATION_FINISHED, and on success also triggers
/// the same refresh gbm_history_refresh() would (the local remote-tracking
/// ref moves).
GBM_API void gbm_push(GbmSessionHandle session,
                      const char* remoteName,
                      const char* branch,
                      int32_t setUpstream,
                      int32_t pushTags,
                      int32_t forceWithLease);

// --- Credential prompts (askpass) -------------------------------------
// Answers or dismisses whichever prompt GBM_EVENT_CREDENTIAL_REQUESTED most
// recently announced. A no-op if none is currently outstanding.

/// Answers the outstanding prompt. A `git` subprocess can ask more than once
/// per invocation (e.g. a password after a username), in which case
/// GBM_EVENT_CREDENTIAL_REQUESTED fires again for the follow-up prompt.
GBM_API void gbm_provide_credential(GbmSessionHandle session, const char* secret);

/// Dismisses the outstanding prompt; the blocked `git` subprocess fails
/// cleanly, exactly as if no credential helper were configured at all.
GBM_API void gbm_cancel_credential(GbmSessionHandle session);

// --- Discovery -------------------------------------------------------------
// A separate handle class from GbmSessionHandle: discovery scans base
// folders and is not tied to any one open repository -- see
// src/core/cache/RepoIndexDb.h / src/core/discovery/Scanner.h.

/// Opens (creating and migrating if needed) the repo index database at
/// `dbPath`, or an in-memory database when `dbPath` is empty. Returns null
/// and populates the staging buffer with a GitError JSON on failure.
GBM_API GbmDiscoveryHandle gbm_discovery_open(const char* dbPath);

GBM_API void gbm_discovery_close(GbmDiscoveryHandle discovery);

/// Registers a folder to scan. Returns the new base folder's row id (>= 0),
/// or a negative GbmErrorCode on failure.
GBM_API int64_t gbm_discovery_add_base_folder(GbmDiscoveryHandle discovery,
                                              const char* path,
                                              int32_t maxDepth,
                                              int32_t followLinks);

/// Scans every enabled base folder synchronously (blocks the calling
/// thread -- callers should run this off the UI isolate, e.g. via Dart's
/// Isolate.run). Returns 0 on success (even if some folders had nothing new)
/// or a negative GbmErrorCode.
GBM_API int32_t gbm_discovery_scan_all(GbmDiscoveryHandle discovery);

/// Populates the staging buffer with every known repository (including
/// those currently missing) as a JSON array. Returns 0 on success.
GBM_API int32_t gbm_discovery_list_repos_json(GbmDiscoveryHandle discovery);

/// Populates the staging buffer with every registered base folder as a JSON
/// array (id/path/enabled/maxDepth/followLinks/lastScan*). Returns 0 on
/// success.
GBM_API int32_t gbm_discovery_base_folders_json(GbmDiscoveryHandle discovery);

/// Unregisters a base folder (its already-discovered repositories stay in
/// the index, matching RepoIndexDb::removeBaseFolder's own contract).
/// Returns 0 on success, or a negative GbmErrorCode.
GBM_API int32_t gbm_discovery_remove_base_folder(GbmDiscoveryHandle discovery, int64_t baseFolderId);

/// Enables/disables a base folder without removing it -- a disabled folder
/// is skipped by gbm_discovery_scan_all() but its known repositories stay
/// listed. Returns 0 on success, or a negative GbmErrorCode.
GBM_API int32_t gbm_discovery_set_base_folder_enabled(GbmDiscoveryHandle discovery,
                                                      int64_t baseFolderId,
                                                      int32_t enabled);
