@TestOn('mac-os || linux')
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:gbm_flutter/data/services/update_installer.dart';

/// These tests **run** the generated updater script against throwaway
/// directories, rather than asserting its text.
///
/// The script is the one piece of this feature that cannot be exercised by
/// the app itself: it runs after the process has exited. Asserting the text
/// would only prove the transcription, not that the swap, the rollback or
/// the still-running-app abort actually behave. Everything here happens
/// inside `Directory.systemTemp`.
///
/// **Scope**: this proves the BSD (macOS) userland. The Linux variant uses
/// the same script with `cp -a` instead of `ditto` and is generated by the
/// same builder, but a GNU-userland run only happens in CI. The PowerShell
/// script cannot be executed here at all and is text-asserted in
/// `update_installer_test.dart`.
void main() {
  late Directory root;

  setUp(() {
    root = Directory.systemTemp.createTempSync('gbm-updater-script');
  });

  tearDown(() {
    if (root.existsSync()) {
      root.deleteSync(recursive: true);
    }
  });

  /// Builds `<root>/<name>/marker.txt` containing [contents].
  Directory dirWithMarker(String name, String contents) {
    final Directory dir = Directory('${root.path}/$name')
      ..createSync(recursive: true);
    File('${dir.path}/marker.txt').writeAsStringSync(contents);
    return dir;
  }

  /// Runs [script] and returns its exit code.
  Future<int> runScript(String script) async {
    final File file = File('${root.path}/updater.sh')
      ..writeAsStringSync(script);
    final ProcessResult result = await Process.run('sh', <String>[file.path]);
    return result.exitCode;
  }

  /// A process that outlives the script's patience, so the "app is still
  /// running" arm can be exercised. Killed by the caller.
  Future<Process> longLivedProcess() => Process.start('sleep', <String>['30']);

  group('the swap', () {
    test('replaces the target and keeps the old one as .gbm-old', () async {
      final Directory target = dirWithMarker('install', 'old');
      final Directory staged = dirWithMarker('staged', 'new');
      final File sentinel = File('${root.path}/relaunched');

      final int code = await runScript(
        buildUnixUpdaterScript(
          pid: 999999, // not running: the wait loop falls straight through
          targetPath: target.path,
          stagedPath: staged.path,
          copyCommand: 'cp -a',
          relaunchCommand: 'touch ${_shq(sentinel.path)}',
          waitTimeout: const Duration(seconds: 2),
        ),
      );

      expect(code, 0);
      expect(File('${target.path}/marker.txt').readAsStringSync(), 'new');
      expect(
        File('${target.path}.gbm-old/marker.txt').readAsStringSync(),
        'old',
        reason: 'the old install must be renamed aside, never deleted',
      );
      expect(sentinel.existsSync(), isTrue);
    });

    // Paths on a real machine contain spaces, and a home directory can
    // contain an apostrophe. Without correct sh quoting the script is a
    // syntax error at best and a wrong-directory delete at worst.
    test('survives a path with a space and a single quote', () async {
      final Directory target = dirWithMarker("it's an install dir", 'old');
      final Directory staged = dirWithMarker("it's staged", 'new');

      final int code = await runScript(
        buildUnixUpdaterScript(
          pid: 999999,
          targetPath: target.path,
          stagedPath: staged.path,
          copyCommand: 'cp -a',
          relaunchCommand: ':',
          waitTimeout: const Duration(seconds: 2),
        ),
      );

      expect(code, 0);
      expect(File('${target.path}/marker.txt').readAsStringSync(), 'new');
    });

    test('waits for the running process to exit first', () async {
      final Directory target = dirWithMarker('install', 'old');
      final Directory staged = dirWithMarker('staged', 'new');
      final Process victim = await Process.start('sleep', <String>['1']);

      final int code = await runScript(
        buildUnixUpdaterScript(
          pid: victim.pid,
          targetPath: target.path,
          stagedPath: staged.path,
          copyCommand: 'cp -a',
          relaunchCommand: ':',
          waitTimeout: const Duration(seconds: 20),
        ),
      );

      expect(code, 0);
      expect(File('${target.path}/marker.txt').readAsStringSync(), 'new');
    });
  });

  // Belt and braces behind `launchUpdater`'s `workingDirectory`. On Windows
  // the inherited directory is what blocked the rename; on Unix it is
  // harmless, but a script that stands inside the directory it is about to
  // move has no business doing so on any platform.
  group('where it runs from', () {
    test('steps out of whatever directory it inherited', () {
      final String script = buildUnixUpdaterScript(
        pid: 999999,
        targetPath: '/tmp/install',
        stagedPath: '/tmp/staged',
        copyCommand: 'cp -a',
        relaunchCommand: ':',
      );

      expect(script, contains(r'cd "$(dirname "$0")"'));
    });

    // Executed, not just asserted: `cd` failing must abort rather than let
    // the swap run from an unknown directory.
    test('still swaps when it runs from the target\'s own parent', () async {
      final Directory target = dirWithMarker('install', 'old');
      final Directory staged = dirWithMarker('staged', 'new');

      final int code = await runScript(
        buildUnixUpdaterScript(
          pid: 999999,
          targetPath: target.path,
          stagedPath: staged.path,
          copyCommand: 'cp -a',
          relaunchCommand: ':',
        ),
      );

      expect(code, 0);
      expect(File('${target.path}/marker.txt').readAsStringSync(), 'new');
    });
  });

  // Once the app has exited there is no channel left to report anything on,
  // so a failed update is otherwise entirely undiagnosable -- which is
  // exactly the position the Windows report left this feature in.
  group('the transcript', () {
    test('records the outcome of a successful swap', () async {
      final Directory target = dirWithMarker('install', 'old');
      final Directory staged = dirWithMarker('staged', 'new');

      final int code = await runScript(
        buildUnixUpdaterScript(
          pid: 999999,
          targetPath: target.path,
          stagedPath: staged.path,
          copyCommand: 'cp -a',
          relaunchCommand: ':',
        ),
      );

      expect(code, 0);
      final String log = File(
        '${root.path}/$kUpdateLogName',
      ).readAsStringSync();
      expect(log, contains(target.path));
      expect(log, contains('exit 0'));
    });

    // The code that matters most: this is the arm nobody could see.
    test('records a rename that could not happen', () async {
      final Directory lock = Directory('${root.path}/lock')
        ..createSync(recursive: true);
      final Directory target = Directory('${lock.path}/install')
        ..createSync(recursive: true);
      final Directory staged = dirWithMarker('staged', 'new');
      await Process.run('chmod', <String>['555', lock.path]);
      addTearDown(() => Process.run('chmod', <String>['755', lock.path]));

      await runScript(
        buildUnixUpdaterScript(
          pid: 999999,
          targetPath: target.path,
          stagedPath: staged.path,
          copyCommand: 'cp -a',
          relaunchCommand: ':',
        ),
      );

      expect(
        File('${root.path}/$kUpdateLogName').readAsStringSync(),
        contains('exit 3'),
      );
    });

    // Truncated, not appended to: a transcript that accumulated every update
    // ever run would bury the one the user is being asked about.
    test('starts fresh rather than appending to the last run', () async {
      final File log = File('${root.path}/$kUpdateLogName')
        ..writeAsStringSync('LEFTOVER FROM AN OLDER UPDATE\n');
      final Directory target = dirWithMarker('install', 'old');
      final Directory staged = dirWithMarker('staged', 'new');

      await runScript(
        buildUnixUpdaterScript(
          pid: 999999,
          targetPath: target.path,
          stagedPath: staged.path,
          copyCommand: 'cp -a',
          relaunchCommand: ':',
        ),
      );

      expect(log.readAsStringSync(), isNot(contains('LEFTOVER')));
    });
  });

  group('the abort arms', () {
    // The arm that matters most: falling through to the swap while the app
    // is still running would leave two instances over a half-replaced
    // install. Timing out must change nothing at all.
    test(
      'changes nothing when the app is still running at the deadline',
      () async {
        final Directory target = dirWithMarker('install', 'old');
        final Directory staged = dirWithMarker('staged', 'new');
        final Process victim = await longLivedProcess();
        addTearDown(() => victim.kill());

        final int code = await runScript(
          buildUnixUpdaterScript(
            pid: victim.pid,
            targetPath: target.path,
            stagedPath: staged.path,
            copyCommand: 'cp -a',
            relaunchCommand: ':',
            waitTimeout: const Duration(milliseconds: 600),
          ),
        );

        expect(code, isNot(0));
        expect(File('${target.path}/marker.txt').readAsStringSync(), 'old');
        expect(Directory('${target.path}.gbm-old').existsSync(), isFalse);
      },
    );

    // The arm that produced the reported Windows symptom: by the time the
    // rename is attempted the app has already exited, so a script that just
    // gives up leaves the user with no running application and no
    // explanation. Nothing here changes the install -- only that a working
    // build is put back on screen.
    //
    // The read-only directory has to be the target's *parent* (renaming
    // needs write permission there, not on the target), which is why the
    // target is nested one level down and the sentinel stays out in `root`:
    // a sentinel written inside the locked directory could not be created
    // either, and the test would pass for the wrong reason.
    test('relaunches the old build when the rename fails', () async {
      final Directory lock = Directory('${root.path}/lock')
        ..createSync(recursive: true);
      final Directory target = Directory('${lock.path}/install')
        ..createSync(recursive: true);
      File('${target.path}/marker.txt').writeAsStringSync('old');
      final Directory staged = dirWithMarker('staged', 'new');
      final File sentinel = File('${root.path}/relaunched');
      await Process.run('chmod', <String>['555', lock.path]);
      addTearDown(() => Process.run('chmod', <String>['755', lock.path]));

      final int code = await runScript(
        buildUnixUpdaterScript(
          pid: 999999,
          targetPath: target.path,
          stagedPath: staged.path,
          copyCommand: 'cp -a',
          relaunchCommand: 'touch ${_shq(sentinel.path)}',
          waitTimeout: const Duration(seconds: 2),
        ),
      );

      expect(code, 3, reason: 'the rename really must have failed');
      expect(File('${target.path}/marker.txt').readAsStringSync(), 'old');
      expect(
        sentinel.existsSync(),
        isTrue,
        reason: 'the app has already exited; something has to bring it back',
      );
    });

    // The one arm that must NOT relaunch: the app never exited, so it is
    // still on screen and a second instance would be worse than nothing.
    test('does not relaunch when the app never exited', () async {
      final Directory target = dirWithMarker('install', 'old');
      final Directory staged = dirWithMarker('staged', 'new');
      final File sentinel = File('${root.path}/relaunched');
      final Process victim = await longLivedProcess();
      addTearDown(() => victim.kill());

      final int code = await runScript(
        buildUnixUpdaterScript(
          pid: victim.pid,
          targetPath: target.path,
          stagedPath: staged.path,
          copyCommand: 'cp -a',
          relaunchCommand: 'touch ${_shq(sentinel.path)}',
          waitTimeout: const Duration(milliseconds: 600),
        ),
      );

      expect(code, 2);
      expect(sentinel.existsSync(), isFalse);
    });

    // The whole reason the old install is renamed rather than deleted.
    test('restores the old install when the copy fails', () async {
      final Directory target = dirWithMarker('install', 'old');
      final Directory staged = dirWithMarker('staged', 'new');
      final File sentinel = File('${root.path}/relaunched');

      final String script = buildUnixUpdaterScript(
        pid: 999999,
        targetPath: target.path,
        stagedPath: staged.path,
        copyCommand: 'cp -a',
        relaunchCommand: 'touch ${_shq(sentinel.path)}',
        waitTimeout: const Duration(seconds: 2),
      );
      // Pulled out from under the script after generation, so the copy is
      // the step that fails rather than the rename.
      staged.deleteSync(recursive: true);

      final int code = await runScript(script);

      expect(code, isNot(0));
      expect(
        File('${target.path}/marker.txt').readAsStringSync(),
        'old',
        reason: 'a failed copy must roll the old install back into place',
      );
      expect(
        sentinel.existsSync(),
        isTrue,
        reason: 'the user must be left with a running app either way',
      );
    });
  });
}

/// Local sh-quoting for values this test puts into a relaunch command.
String _shq(String value) => "'${value.replaceAll("'", r"'\''")}'";
