// The commit graph's lane palette: how many colours there are, and where they
// sit on the colour wheel.
//
// Both are contracts with code that cannot import this file. The count is
// shared with the C++ core, which emits `0 .. kPaletteSize - 1`; the *order*
// is shared with `LaneAllocator::colorForSeed`, which spreads a new lane away
// from its neighbours by doing arithmetic on the index and never looking at a
// colour. Nothing but this file checks either, and the count already drifted
// once: the palette shipped with six entries against a `kPaletteSize` of 12,
// so `% length` folded colour 6 onto 0 -- the trunk's own colour -- and 7..11
// onto 1..5, with no error anywhere and a badge-free symptom (branches that
// merely looked alike).
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:gbm_flutter/theme/tokens.dart';

/// OkLCH hue in degrees.
///
/// Written here rather than in `lib/` on purpose: it is the independent
/// oracle the palette is checked against, and a palette generated by the
/// same code it is verified with cannot disagree with itself. Same reason
/// `sameLogicalFile` lives in its test file.
///
/// HSL would be the cheap alternative and it would be wrong: its wheel is not
/// perceptually even, so these twelve colours are 12.4 deg apart in the teal
/// band and 68 deg apart in the green one. An HSL assertion would read an
/// evenly-spaced palette as uneven, and would pass an uneven one that happened
/// to be even in HSL.
double _okHue(Color color) {
  double toLinear(double c) =>
      c <= 0.04045 ? c / 12.92 : math.pow((c + 0.055) / 1.055, 2.4).toDouble();

  final double r = toLinear(color.r);
  final double g = toLinear(color.g);
  final double b = toLinear(color.b);

  double cbrt(double x) => math.pow(x, 1 / 3).toDouble();
  final double l = cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  final double m = cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  final double s = cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);

  final double a = 1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s;
  final double bb = 0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s;
  return (math.atan2(bb, a) * 180 / math.pi + 360) % 360;
}

/// The `kPaletteSize` the C++ core actually compiles with, read from its
/// header rather than copied here -- a copy is what let the two drift.
int _corePaletteSize() {
  final File header = File('../src/core/graph/GraphSnapshot.h');
  expect(
    header.existsSync(),
    isTrue,
    reason:
        'GraphSnapshot.h must be readable from the package root so this test '
        'can compare against the real constant. If the layout moved, fix the '
        'path -- do not soften this to a hardcoded 12, which is exactly the '
        'copy that drifted before.',
  );
  final RegExp pattern = RegExp(
    r'constexpr\s+std::uint8_t\s+kPaletteSize\s*=\s*(\d+)\s*;',
  );
  final RegExpMatch? match = pattern.firstMatch(header.readAsStringSync());
  expect(match, isNotNull, reason: 'kPaletteSize not found in GraphSnapshot.h');
  return int.parse(match!.group(1)!);
}

void main() {
  final Map<GbmThemeVariant, GbmColors> themes = <GbmThemeVariant, GbmColors>{
    for (final GbmThemeVariant v in GbmThemeVariant.values) v: tokensFor(v),
  };

  test('every theme offers exactly as many lanes as the core emits', () {
    final int size = _corePaletteSize();
    expect(size, 12, reason: 'sanity: the core has not changed under us');

    themes.forEach((GbmThemeVariant variant, GbmColors colors) {
      expect(
        colors.graphLanes.length,
        size,
        reason:
            '$variant has ${colors.graphLanes.length} lane colours for '
            '$size colour ids. Any shortfall is silent: the painter takes '
            '`color % length`, so the surplus ids impersonate lower ones '
            'and one of them impersonates the trunk.',
      );
    });
  });

  test('a theme never spends two lanes on the same colour', () {
    themes.forEach((GbmThemeVariant variant, GbmColors colors) {
      final Set<int> distinct = colors.graphLanes
          .map((Color c) => c.toARGB32())
          .toSet();
      expect(
        distinct.length,
        colors.graphLanes.length,
        reason: '$variant repeats a lane colour',
      );
    });
  });

  test('lane i sits 30 degrees round the wheel from lane i-1, in every '
      'theme', () {
    // This is the half `LaneAllocator::colorForSeed` depends on. It scores a
    // candidate index by `min(d, 12 - d)` against its neighbours' indices and
    // never sees a colour, so that number is only a hue distance while this
    // holds. Reordering the list -- or slipping one entry in -- would leave
    // the core happily "maximising" a distance that no longer means anything,
    // and nothing would throw.
    themes.forEach((GbmThemeVariant variant, GbmColors colors) {
      final double first = _okHue(colors.graphLanes.first);
      for (int i = 0; i < colors.graphLanes.length; i++) {
        final double expected = (first + 30 * i) % 360;
        final double actual = _okHue(colors.graphLanes[i]);
        final double delta = math.min(
          (actual - expected) % 360,
          (expected - actual) % 360,
        );
        expect(
          delta,
          lessThan(1.5),
          reason:
              '$variant lane $i is at ${actual.toStringAsFixed(1)} deg, '
              'expected ${expected.toStringAsFixed(1)}. 8-bit rounding costs '
              'at most 0.62 deg, so anything past 1.5 is a reordering or a '
              'hand-edited colour, not quantisation.',
        );
      }
    });
  });

  test('lane 0 is the accent, which is what makes the trunk the accent', () {
    // `colorForSeed` returns 0 for lane 0 unconditionally, and spec's
    // `--graph-lane-1` is `var(--accent-500)`. Dark keeps accentHover
    // instead -- the brighter blue against #0D1117 -- which predates this
    // round and is left alone.
    expect(
      tokensFor(
        GbmThemeVariant.neutralProfessional,
      ).graphLanes.first.toARGB32(),
      tokensFor(GbmThemeVariant.neutralProfessional).accent.toARGB32(),
    );
    expect(
      tokensFor(GbmThemeVariant.lightIde).graphLanes.first.toARGB32(),
      tokensFor(GbmThemeVariant.lightIde).accent.toARGB32(),
    );
    expect(
      tokensFor(GbmThemeVariant.darkTechnical).graphLanes.first.toARGB32(),
      tokensFor(GbmThemeVariant.darkTechnical).accentHover.toARGB32(),
    );
  });
}
